/*Transforme vital table to obsclin MU data*/

/*Records of height not exsit in OBSCLIN table*/

CREATE OR replace TABLE not_exsit_in_obslcin_ht as
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A 
WHERE HT  IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_date,b.obsclin_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'height (cm)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (feet)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (inches)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length measured%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (inches calc)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length estimated%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length dosing%');

/*Create table for data exists in vital not obsclin*/
CREATE OR REPLACE TABLE   insert_obsc_ht AS
SELECT a.* FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A
 JOIN grouse_db_quail.dq_clean_table.not_exsit_in_obslcin_ht b ON b.patid = a.patid
 AND b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;

/*Records of weight not exsit in OBSCLIN table*/
 
/*create table for wt data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A 
WHERE WT IS NOT NULL
MINUS SELECT b.patid, b.obsclin_date,b.obsclin_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'weight (lbs calc)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight (kg)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight (lbs)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight measured%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight for height/length percentile%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight percentile%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight estimated%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight-dialysis%');

 /*Records of BMI not exsit in OBSCLIN table*/ 

/*create table for bmi data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A 
WHERE original_bmi  IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_date,b.obsclin_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_OBS_CLIN  B 
WHERE  (lower (b.RAW_OBSCLIN_NAME) LIKE  'bmi%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'bmi percentile%'
);

/*Create table for data exists in vital not obsclin*/
CREATE OR REPLACE TABLE  insert_obsc_bmi AS
SELECT  a.* FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A
JOIN grouse_db_quail.dq_clean_table.Not_exists_in_obsclin_bmi b ON  b.patid = a.patid
AND  b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;


/*Records of daistolic blood prossure (DBP) not exsit in OBSCLIN table*/  

/*create table for dbp data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A 
WHERE  diastolic IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_date,b.obsclin_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%diastolic%'
OR upper (raw_obsclin_name) LIKE '%dbp%'
);

/*Create table for data exists in vital not obsclin*/
Create OR REPALCE TABLE   insert_obsc_dbp AS
SELECT a.* FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A
JOIN grouse_db_quail.dq_clean_table.NOT_EXISTS_IN_OBSCLIN_DBP b ON b.patid = a.patid
AND b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;

/*Records of systolic blood prossure (SBP) not exsit in OBSCLIN table*/

/*create table for sbp data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A 
WHERE  systolic IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_date,b.obsclin_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.LDS_OBS_CLIN  B 
WHERE  (lower (raw_obsclin_name) LIKE '%systolic%'
 or upper (raw_obsclin_name) LIKE '%sbp%'
); 


/*Create table for data exists in vital not obsclin*/
CREATE OR REPLACE TABLE insert_obsc_sbp AS
SELECT  a.* FROM GROUSE_DB.PCORNET_CDM_MU.LDS_VITAL A
JOIN grouse_db_quail.dq_clean_table.NOT_EXISTS_IN_OBSCLIN_sBP b ON b.patid = a.patid
AND b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;


/*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE MU_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH MU_vital_insert_wt AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
    MEASURE_DATE AS OBSCLIN_DATE , 
	NULL AS OBSCLIN_SOURCE,
	WT AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'29463-7' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'WT' AS RAW_OBSCLIN_NAME,
	'LBS' AS OBSCLIN_RESULT_UNIT,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	WT AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'29463-7' AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_TIME AS OBSCLIN_TIME,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'LBS' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	'27113001' AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.insert_obsc_wt),

MU_vital_insert_HT AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
    MEASURE_DATE AS OBSCLIN_DATE , 
	NULL AS OBSCLIN_SOURCE,
	HT AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'8302-2' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'HT' AS RAW_OBSCLIN_NAME,
	'INCH(S)' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	HT AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'8302-2'  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_TIME AS OBSCLIN_TIME,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'INCH(S)' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	'50373000' AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_HT),

MU_vital_insert_BMI AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
    MEASURE_DATE AS OBSCLIN_DATE , 
	NULL AS OBSCLIN_SOURCE,
	original_bmi AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'39156-5' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'BMI' AS RAW_OBSCLIN_NAME,
	NULL AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	original_bmi AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'39156-5'  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_TIME AS OBSCLIN_TIME,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	'60621009' AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_BMI),

MU_vital_insert_DBP AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
    MEASURE_DATE AS OBSCLIN_DATE , 
	NULL AS OBSCLIN_SOURCE,
	diastolic AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'8462-4' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'DBP' AS RAW_OBSCLIN_NAME,
	'mmHg' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	diastolic AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'8462-4'  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_TIME AS OBSCLIN_TIME,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'mmHg' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_DBP),

MU_vital_insert_SBP AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
    MEASURE_DATE AS OBSCLIN_DATE , 
	NULL AS OBSCLIN_SOURCE,
    systolic AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'8480-6' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'SBP' AS RAW_OBSCLIN_NAME,
	'mmHg' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	systolic AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'8480-6'  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_TIME AS OBSCLIN_TIME,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'mmHg' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_SBP)

SELECT * FROM MU_vital_insert_WT
UNION
SELECT * FROM MU_vital_insert_HT
UNION
SELECT * FROM MU_vital_insert_BMI
UNION
SELECT * FROM MU_vital_insert_DBP
UNION
SELECT * FROM MU_vital_insert_SBP);



/*Modify colunm data type*/
CREATE OR REPLACE TABLE Modified_INSERT_IN_OBC_ALL AS

SELECT RAW_OBSCLIN_MODIFIER,
     OBSCLIN_DATE , 
	OBSCLIN_SOURCE,
    CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
	 OBSCLIN_RESULT_QUAL,
	OBSCLIN_START_TIME,
	RAW_OBSCLIN_CODE ,
	RAW_OBSCLIN_TYPE,
	 RAW_OBSCLIN_NAME,
	OBSCLIN_RESULT_UNIT, ---NO UNITS IN VITAL
	OBSCLIN_TYPE,
	OBSCLIN_PROVIDERID,
	CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM ,
	 OBSCLIN_STOP_DATE ,
	OBSCLIN_CODE ,
	PATID,
	 OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	 OBSCLIN_TIME,
	OBSCLIN_START_DATE,
	RAW_OBSCLIN_UNIT ,
	 OBSCLINID ,
	 OBSCLIN_RESULT_SNOMED,
	OBSCLIN_ABN_IND,
    OBSCLIN_STOP_TIME ,
     OBSCLIN_RESULT_TEXT  

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MU_INSERT_OBSCLIN_VITAL_SIGNS
;

/*The final linked table*/
CREATE OR REPLACE TABLE linked_vital_obsclin_table AS
SELECT * FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MODIFIED_INSERT_IN_OBC_ALL
UNION 
SELECT * FROM GROUSE_DB.PCORNET_CDM_MU.LDS_OBS_CLIN;
;

////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////ALLINA////////////////////////////////////////////////////////////


 /*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE ALLINA_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH ALLINA_vital_insert_wt AS (SELECT 
    NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
	WT AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'29463-7' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'WT' AS RAW_OBSCLIN_NAME,
	'LBS' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	WT AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'29463-7' AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'LBS' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	'27113001' AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE WT IS NOT NULL ),

ALLINA_vital_insert_HT AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
	HT AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'8302-2' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'HT' AS RAW_OBSCLIN_NAME,
	'INCH(S)' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	HT AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'8302-2'  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'INCH(S)' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	'50373000' AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
    NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE HT IS NOT NULL ),

ALLINA_vital_insert_BMI AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
	original_bmi AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'39156-5' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'BMI' AS RAW_OBSCLIN_NAME,
	NULL AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	original_bmi AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'39156-5'  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	'60621009' AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
    NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE ORIGINAL_BMI IS NOT NULL ),

ALLINA_vital_insert_DBP AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
	diastolic AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'8462-4' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'DBP' AS RAW_OBSCLIN_NAME,
	'mmHg' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	diastolic AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'8462-4' AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'mmHg' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
        NULL AS OBSCLIN_RESULT_TEXT 
 FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE DIASTOLIC IS NOT NULL ),

ALLINA_vital_insert_SBP AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER, 
	NULL AS OBSCLIN_SOURCE,
    systolic AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'8480-6' AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'SBP' AS RAW_OBSCLIN_NAME,
	'mmHg' AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	systolic AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	'8480-6' AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	'mmHg' AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
    NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE SYSTOLIC IS NOT NULL )

SELECT * FROM ALLINA_vital_insert_WT
UNION
SELECT * FROM ALLINA_vital_insert_HT
UNION
SELECT * FROM ALLINA_vital_insert_BMI
UNION
SELECT * FROM ALLINA_vital_insert_DBP
UNION
SELECT * FROM ALLINA_vital_insert_SBP);

 -----
/*Create table for smoking data*/
CREATE OR REPLACE TABLE ALLINA_SMOKING_DATA AS (
WITH ALLINA_vital_insert_smoking AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
    smoking AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	NULL AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'smoking' AS RAW_OBSCLIN_NAME,
	NULL AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_NUM,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
    NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE  SMOKING IS NOT NULL ),

ALLINA_vital_insert_TOBACCO AS (SELECT 
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
    tobacco AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	NULL AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'tobacco' AS RAW_OBSCLIN_NAME,
	NULL AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
    NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE TOBACCO IS NOT NULL  ),

ALLINA_vital_insert_TOBACCO_TYPE AS (SELECT 
    NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS OBSCLIN_SOURCE,
    tobacco_type AS RAW_OBSCLIN_RESULT,
	NULL AS  OBSCLIN_RESULT_QUAL,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	NULL AS RAW_OBSCLIN_CODE ,
	NULL AS RAW_OBSCLIN_TYPE,
	'tobacco_type' AS RAW_OBSCLIN_NAME,
	NULL AS OBSCLIN_RESULT_UNIT, 
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL  AS  OBSCLIN_CODE ,
	PATID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS OBSCLIN_STOP_TIME ,
    NULL AS OBSCLIN_RESULT_TEXT 
FROM GROUSE_DB.PCORNET_CDM_ALLINA.LDS_VITAL
WHERE TOBACCO_TYPE IS NOT NULL )

SELECT * FROM ALLINA_VITAL_INSERT_SMOKING
UNION
SELECT * FROM ALLINA_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM ALLINA_VITAL_INSERT_TOBACCO_TYPE);



/*Modify colunm data type*/
CREATE OR REPLACE TABLE Modified_allina_INSERT_IN_OBC_vital AS

SELECT RAW_OBSCLIN_MODIFIER,
	OBSCLIN_SOURCE,
    CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
	 OBSCLIN_RESULT_QUAL,
	OBSCLIN_START_TIME,
	RAW_OBSCLIN_CODE ,
	RAW_OBSCLIN_TYPE,
	 RAW_OBSCLIN_NAME,
	OBSCLIN_RESULT_UNIT, 
	OBSCLIN_TYPE,
	OBSCLIN_PROVIDERID,
	CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM ,
	 OBSCLIN_STOP_DATE ,
	OBSCLIN_CODE ,
	PATID,
	 OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID , 
	OBSCLIN_START_DATE,
	RAW_OBSCLIN_UNIT ,
	 OBSCLINID ,
	 OBSCLIN_RESULT_SNOMED,
	OBSCLIN_ABN_IND,
    OBSCLIN_STOP_TIME ,
     OBSCLIN_RESULT_TEXT  

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.ALLINA_INSERT_OBSCLIN_VITAL_SIGNS
;


/*Modify colunm data type*/
CREATE OR REPLACE TABLE  Modified_allina_INSERT_IN_OBC_tobacoo AS

SELECT RAW_OBSCLIN_MODIFIER,
	OBSCLIN_SOURCE,
    CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
	 OBSCLIN_RESULT_QUAL,
	OBSCLIN_START_TIME,
	RAW_OBSCLIN_CODE ,
	RAW_OBSCLIN_TYPE,
	 RAW_OBSCLIN_NAME,
	OBSCLIN_RESULT_UNIT, 
	OBSCLIN_TYPE,
	OBSCLIN_PROVIDERID,
	CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM ,
	 OBSCLIN_STOP_DATE ,
	OBSCLIN_CODE ,
	PATID,
	 OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID ,
	OBSCLIN_START_DATE,
	RAW_OBSCLIN_UNIT ,
	 OBSCLINID ,
	 OBSCLIN_RESULT_SNOMED,
	OBSCLIN_ABN_IND,
    OBSCLIN_STOP_TIME ,
     OBSCLIN_RESULT_TEXT  

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.ALLINA_SMOKING_DATA
;
-------------------------------------
-------------------------------------
/*union both tables */
create or replace table Allina_linked_vital_obsclin as 
select * from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.Modified_allina_INSERT_IN_OBC_vital
union
select * from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.modified_allina_insert_in_obc_tobacoo
union
select * from GROUSE_DB.PCORNET_CDM_ALLINA.DEID_OBS_CLIN;


////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////IHC////////////////////////////////////////////////////////////


 /*vital Wt inserted to obsclin */

CREATE OR REPLACE TABLE IHC_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH IHC_vital_insert_wt AS (SELECT 
	NULL AS OBSCLIN_PROVIDERID,
    MEASURE_DATE AS OBSCLIN_STOP_DATE,
	PATID ,
    '29463-7' AS RAW_OBSCLIN_CODE,
    'LBS' AS OBSCLIN_RESULT_UNIT ,
    '27113001' AS OBSCLIN_RESULT_SNOMED,
    NULL AS	OBSCLIN_ABN_IND,
    MEASURE_DATE AS OBSCLIN_START_DATE,
    NULL AS	OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID,
    NULL AS OBSCLIN_RESULT_TEXT,
    NULL AS	OBSCLIN_STOP_TIME,
    NULL AS	OBSCLIN_TYPE ,
    'LBS' AS RAW_OBSCLIN_UNIT,
    WT AS OBSCLIN_RESULT_NUM ,
    NULL AS RAW_OBSCLIN_TYPE,
    NULL AS	OBSCLIN_RESULT_QUAL,
    NULL AS OBSCLINID,
    NULL AS RAW_OBSCLIN_MODIFIER,
    NULL AS OBSCLIN_RESULT_TXT,
    WT AS RAW_OBSCLIN_RESULT,
    MEASURE_TIME  AS OBSCLIN_START_TIME,
    NULL AS	RESULT_UNIT ,
   'WT' AS RAW_OBSCLIN_NAME ,
   '29463-7' AS OBSCLIN_CODE ,
    NULL AS	OBSCLIN_SOURCE 
FROM GROUSE_DB.PCORNET_CDM_IHC.LDS_VITAL
WHERE WT IS NOT NULL  ),

IHC_vital_insert_HT AS (SELECT 
	NULL AS OBSCLIN_PROVIDERID,
    MEASURE_DATE AS OBSCLIN_STOP_DATE,
	PATID ,
    '8302-2' AS RAW_OBSCLIN_CODE,
    'INCH(S)' AS OBSCLIN_RESULT_UNIT ,
   '50373000' AS OBSCLIN_RESULT_SNOMED,
    NULL AS	OBSCLIN_ABN_IND,
    MEASURE_DATE AS OBSCLIN_START_DATE,
    NULL AS	OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID,
    NULL AS OBSCLIN_RESULT_TEXT,
    NULL AS	OBSCLIN_STOP_TIME,
    NULL AS	OBSCLIN_TYPE ,
    'INCH(S)' AS RAW_OBSCLIN_UNIT,
    HT AS OBSCLIN_RESULT_NUM ,
    NULL AS RAW_OBSCLIN_TYPE,
    NULL AS	OBSCLIN_RESULT_QUAL,
    NULL AS OBSCLINID,
    NULL AS RAW_OBSCLIN_MODIFIER,
    NULL AS OBSCLIN_RESULT_TXT,
    HT AS RAW_OBSCLIN_RESULT,
    MEASURE_TIME  AS OBSCLIN_START_TIME,
    NULL AS	RESULT_UNIT ,
    'HT' AS RAW_OBSCLIN_NAME ,
    '8302-2' AS	OBSCLIN_CODE ,
    NULL AS	OBSCLIN_SOURCE 
FROM GROUSE_DB.PCORNET_CDM_IHC.LDS_VITAL
WHERE HT IS NOT NULL),

IHC_vital_insert_BMI AS (SELECT 
	NULL AS OBSCLIN_PROVIDERID,
    MEASURE_DATE AS OBSCLIN_STOP_DATE,
	PATID ,
    '39156-5' AS RAW_OBSCLIN_CODE,
    NULL AS OBSCLIN_RESULT_UNIT ,
    '60621009' AS OBSCLIN_RESULT_SNOMED,
    NULL AS	OBSCLIN_ABN_IND,
    MEASURE_DATE AS OBSCLIN_START_DATE,
    NULL AS	OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID,
    NULL AS OBSCLIN_RESULT_TEXT,
    NULL AS	OBSCLIN_STOP_TIME,
    NULL AS	OBSCLIN_TYPE ,
    NULL AS RAW_OBSCLIN_UNIT,
    original_bmi AS OBSCLIN_RESULT_NUM ,
    NULL AS RAW_OBSCLIN_TYPE,
    NULL AS	OBSCLIN_RESULT_QUAL,
    NULL AS OBSCLINID,
    NULL AS RAW_OBSCLIN_MODIFIER,
    NULL AS OBSCLIN_RESULT_TXT,
    original_bmi AS RAW_OBSCLIN_RESULT,
    MEASURE_TIME  AS OBSCLIN_START_TIME,
    NULL AS	RESULT_UNIT ,
   'BMI' AS RAW_OBSCLIN_NAME ,
   '39156-5' AS OBSCLIN_CODE ,
    NULL AS	OBSCLIN_SOURCE 
FROM GROUSE_DB.PCORNET_CDM_IHC.LDS_VITAL
WHERE ORIGINAL_BMI IS NOT NULL),

IHC_vital_insert_DBP AS ( SELECT 
	NULL AS OBSCLIN_PROVIDERID,
    MEASURE_DATE AS OBSCLIN_STOP_DATE,
	PATID ,
    '8462-4' AS RAW_OBSCLIN_CODE,
    'mmHg' AS OBSCLIN_RESULT_UNIT ,
    NULL AS OBSCLIN_RESULT_SNOMED,
    NULL AS	OBSCLIN_ABN_IND,
    MEASURE_DATE AS OBSCLIN_START_DATE,
    NULL AS	OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID,
    NULL AS OBSCLIN_RESULT_TEXT,
    NULL AS	OBSCLIN_STOP_TIME,
    NULL AS	OBSCLIN_TYPE ,
    NULL AS RAW_OBSCLIN_UNIT,
    diastolic AS OBSCLIN_RESULT_NUM ,
    NULL AS RAW_OBSCLIN_TYPE,
    NULL AS	OBSCLIN_RESULT_QUAL,
    NULL AS OBSCLINID,
    NULL AS RAW_OBSCLIN_MODIFIER,
    NULL AS OBSCLIN_RESULT_TXT,
    diastolic AS RAW_OBSCLIN_RESULT,
    MEASURE_TIME  AS OBSCLIN_START_TIME,
    'mmHg' AS	RESULT_UNIT ,
   'DBP' AS RAW_OBSCLIN_NAME ,
    '8462-4' AS	OBSCLIN_CODE ,
    NULL AS	OBSCLIN_SOURCE 
 FROM GROUSE_DB.PCORNET_CDM_IHC.LDS_VITAL
WHERE DIASTOLIC IS NOT NULL ),

IHC_vital_insert_SBP AS (SELECT
    NULL AS OBSCLIN_PROVIDERID,
    MEASURE_DATE AS OBSCLIN_STOP_DATE,
	PATID ,
    '8480-6' AS RAW_OBSCLIN_CODE,
    'mmHg' AS OBSCLIN_RESULT_UNIT ,
    NULL AS OBSCLIN_RESULT_SNOMED,
    NULL AS	OBSCLIN_ABN_IND,
    MEASURE_DATE AS OBSCLIN_START_DATE,
    NULL AS	OBSCLIN_RESULT_MODIFIER,
	ENCOUNTERID,
    NULL AS OBSCLIN_RESULT_TEXT,
    NULL AS	OBSCLIN_STOP_TIME,
    NULL AS	OBSCLIN_TYPE ,
    NULL AS RAW_OBSCLIN_UNIT,
    systolic AS OBSCLIN_RESULT_NUM ,
    NULL AS RAW_OBSCLIN_TYPE,
    NULL AS	OBSCLIN_RESULT_QUAL,
    NULL AS OBSCLINID,
    NULL AS RAW_OBSCLIN_MODIFIER,
    NULL AS OBSCLIN_RESULT_TXT,
    systolic AS RAW_OBSCLIN_RESULT,
    MEASURE_TIME  AS OBSCLIN_START_TIME,
    'mmHg' AS	RESULT_UNIT ,
   'SBP' AS RAW_OBSCLIN_NAME ,
   '8480-6' AS	OBSCLIN_CODE ,
   NULL AS	OBSCLIN_SOURCE 
FROM GROUSE_DB.PCORNET_CDM_IHC.LDS_VITAL
WHERE SYSTOLIC IS NOT NULL )

SELECT * FROM IHC_vital_insert_WT
UNION
SELECT * FROM IHC_vital_insert_HT
UNION
SELECT * FROM IHC_vital_insert_BMI
UNION
SELECT * FROM IHC_vital_insert_DBP
UNION
SELECT * FROM IHC_vital_insert_SBP);

 ------------------------------------




/*Modify colunm data type*/
CREATE OR REPLACE TABLE Modified_ihc_INSERT_IN_OBC_ALL AS

SELECT
 OBSCLIN_PROVIDERID,
 OBSCLIN_STOP_DATE,
 PATID ,
 RAW_OBSCLIN_CODE,
 OBSCLIN_RESULT_UNIT ,
 OBSCLIN_RESULT_SNOMED,
 OBSCLIN_ABN_IND,
 OBSCLIN_START_DATE,
 OBSCLIN_RESULT_MODIFIER,
 ENCOUNTERID,
 OBSCLIN_RESULT_TEXT,
 OBSCLIN_STOP_TIME,
 OBSCLIN_TYPE ,
 RAW_OBSCLIN_UNIT,
 CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
 RAW_OBSCLIN_TYPE,
 OBSCLIN_RESULT_QUAL,
 OBSCLINID,
 RAW_OBSCLIN_MODIFIER,
 OBSCLIN_RESULT_TXT,
 CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
 OBSCLIN_START_TIME,
 RESULT_UNIT ,
 RAW_OBSCLIN_NAME ,
 OBSCLIN_CODE ,
 OBSCLIN_SOURCE 
 

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.IHC_INSERT_OBSCLIN_VITAL_SIGNS
;


/*The final linked table*/
CREATE OR REPLACE TABLE  linked_ihc_vital_obsclin_table AS
SELECT *
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MODIFIED_ihc_INSERT_IN_OBC_ALL
UNION 
SELECT *  FROM GROUSE_DB.PCORNET_CDM_IHC.LDS_OBS_CLIN;
;
SELECT* 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.linked_ihc_vital_obsclin_table
;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////KUMC////////////////////////////////////////////////////////////////////////

---All vital data alrady exist in obclin table
/*Records of ht not exsit in OBSCLIN table*/
---all records in vital are already exist in obsclin
--CREATE OR REPLACE TABLE KUMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE HT IS NOT NULL
MINUS ( SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'ht%'
 ));
  
//*wt*/

 
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE WT IS NOT NULL
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'wt%'
 );

//*BMI*/


/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE original_bmi IS NOT NULL
MINUS (SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE  (lower (b.RAW_OBSCLIN_NAME) LIKE  '%bmi%'
 
));

//*DBP*/

 
/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE  diastolic IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%diastolic%'
 
);


//*SBP*/

/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE  systolic IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%systolic%'
 
); 

//*smoking*/



/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE  smoking IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%smoking%'
 
); 


//*tobacco*/


/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE tobacco IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%tobacco'
 
); 

//*tobacco_type*/


/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE  tobacco_type  IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE  (lower (raw_obsclin_name) LIKE  'tobacco_type'
 
); 

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////MRCI////////////////////////////////////////////////////////////////
/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE MCRI_Not_exists_in_obsclin_all AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MCRI.LDS_VITAL  A 

MINUS (SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM  GROUSE_DB.PCORNET_CDM_MCRI.LDS_OBS_CLIN B )

 
; 


/*Create table for data exists in vital not obsclin*/
Create or replace table  mcri_insert_obsclin as
 select distinct a.* from GROUSE_DB.PCORNET_CDM_MCRI.LDS_VITAL  A
 join grouse_db_quail.dq_clean_table.mcri_not_exists_in_obsclin_all b on b.patid = a.patid
 and b.encounterid = a.encounterid and b.MEASURE_DATE = a.measure_date and b.measure_time = a.measure_time;


/*vital sings nserted to obsclin*/


CREATE OR REPLACE TABLE  MCRI_vital_SINGS AS (
WITH MCRI_vital_insert_wt AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
WT AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
'LBS' AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
'LBS' AS	RAW_OBSCLIN_UNIT ,
'29463-7' AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
'29463-7' AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
WT AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'WT' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where wt is not null),

MCRI_vital_insert_ht AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
HT AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
'INCH(S)' AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
'INCH(S)' AS RAW_OBSCLIN_UNIT ,
'8302-2' AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
'8302-2' AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
HT AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'HT' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where Ht is not null),

MCRI_vital_insert_BMI AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
ORIGINAL_BMI AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
NULL AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
NULL AS	RAW_OBSCLIN_UNIT ,
'39156-5' AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
'39156-5' AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
ORIGINAL_BMI AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'BMI' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where ORIGINAL_BMI is not null),

MCRI_vital_insert_DBP AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
DIASTOLIC AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
'mmHg' AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
'mmHg' AS	RAW_OBSCLIN_UNIT ,
'8462-4' AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
'8462-4' AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
DIASTOLIC AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'DIASTOLIC' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where DIASTOLIC is not null), 

 MCRI_vital_insert_SBP AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
SYSTOLIC AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
'mmHg' AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
'mmHg' AS	RAW_OBSCLIN_UNIT ,
'8480-6' AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
'8480-6' AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
SYSTOLIC AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'SYSTOLIC' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where SYSTOLIC is not null)


SELECT * FROM MCRI_vital_insert_WT
UNION
SELECT * FROM MCRI_vital_insert_HT
UNION
SELECT * FROM MCRI_vital_insert_BMI
UNION
SELECT * FROM MCRI_vital_insert_DBP
UNION
SELECT * FROM MCRI_vital_insert_SBP

)


;
-------
/*Create table for smoking data*/
CREATE OR REPLACE TABLE MCRI_SMOKING_DATA AS (
WITH MCRI_vital_insert_smoking AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
NULL AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
NULL AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
NULL AS	RAW_OBSCLIN_UNIT ,
NULL AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
NULL AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
SMOKING AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'SMOKING' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where SMOKING NOT IN ('NI','','NULL')),
MCRI_vital_insert_TOBACCO AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
NULL AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
NULL AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
NULL AS	RAW_OBSCLIN_UNIT ,
NULL AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
NULL AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
TOBACCO AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'TOBACCO' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where TOBACCO  NOT IN ('NI','','NULL')),
MCRI_vital_insert_TOBACCO_TYPE AS (SELECT 
	NULL AS OBSCLIN_RESULT_QUAL ,
NULL AS	OBSCLINID,
NULL AS OBSCLIN_RESULT_NUM ,
MEASURE_TIME AS	OBSCLIN_STOP_TIME ,
MEASURE_TIME AS OBSCLIN_START_TIME ,
NULL AS	OBSCLIN_RESULT_UNIT ,
NULL AS	OBSCLIN_SOURCE ,
MEASURE_DATE AS	OBSCLIN_START_DATE,
NULL AS	RAW_OBSCLIN_TYPE ,
NULL AS	RAW_OBSCLIN_UNIT ,
NULL AS	OBSCLIN_CODE,
MEASURE_DATE AS	OBSCLIN_STOP_DATE ,
NULL AS	OBSCLIN_TYPE ,
NULL AS	OBSCLIN_PROVIDERID,
NULL AS	RAW_OBSCLIN_CODE,
NULL AS	OBSCLIN_ABN_IND,
TOBACCO_TYPE AS	RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
NULL AS	OBSCLIN_RESULT_SNOMED,
NULL AS	OBSCLIN_RESULT_TEXT,
	PATID ,
NULL AS OBSCLIN_RESULT_MODIFIER ,
NULL AS  RAW_OBSCLIN_MODIFIER ,
'TOBACCO_TYPE' AS RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
where TOBACCO_TYPE  NOT IN ('NI','','NULL'))
SELECT * FROM MCRI_VITAL_INSERT_SMOKING
UNION
SELECT * FROM MCRI_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM MCRI_VITAL_INSERT_TOBACCO_TYPE);
-----------------
/*Change variable type for vital data*/
CREATE OR REPLACE TABLE MCRI_MODIFIED_INSERT_IN_OBC_vital AS 
SELECT 
OBSCLIN_RESULT_QUAL ,
OBSCLINID,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM ,
OBSCLIN_STOP_TIME ,
OBSCLIN_START_TIME ,
OBSCLIN_RESULT_UNIT ,
OBSCLIN_SOURCE ,
OBSCLIN_START_DATE,
RAW_OBSCLIN_TYPE ,
RAW_OBSCLIN_UNIT ,
OBSCLIN_CODE,
OBSCLIN_STOP_DATE ,
OBSCLIN_TYPE ,
OBSCLIN_PROVIDERID,
RAW_OBSCLIN_CODE,
OBSCLIN_ABN_IND,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
OBSCLIN_RESULT_SNOMED,
OBSCLIN_RESULT_TEXT,
	PATID ,
OBSCLIN_RESULT_MODIFIER ,
RAW_OBSCLIN_MODIFIER ,
RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_VITAL_SINGS;
------
/*Change variable type for smoking data*/
CREATE OR REPLACE TABLE MCRI_MODIFIED_INSERT_IN_OBC_smoking AS 
SELECT 
OBSCLIN_RESULT_QUAL ,
OBSCLINID,
 OBSCLIN_RESULT_NUM ,
OBSCLIN_STOP_TIME ,
OBSCLIN_START_TIME ,
OBSCLIN_RESULT_UNIT ,
OBSCLIN_SOURCE ,
OBSCLIN_START_DATE,
RAW_OBSCLIN_TYPE ,
RAW_OBSCLIN_UNIT ,
OBSCLIN_CODE,
OBSCLIN_STOP_DATE ,
OBSCLIN_TYPE ,
OBSCLIN_PROVIDERID,
RAW_OBSCLIN_CODE,
OBSCLIN_ABN_IND,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
	ENCOUNTERID,
OBSCLIN_RESULT_SNOMED,
OBSCLIN_RESULT_TEXT,
	PATID ,
OBSCLIN_RESULT_MODIFIER ,
RAW_OBSCLIN_MODIFIER ,
RAW_OBSCLIN_NAME
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_SMOKING_DATA;
------
SELECT * FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_MODIFIED_INSERT_IN_OBC_SMOKING
UNION 
SELECT * FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_MODIFIED_INSERT_IN_OBC_VITAL
UNION 
SELECT * FROM GROUSE_DB.PCORNET_CDM_MCRI.LDS_OBS_CLIN;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////MCW////////////////////////////////////////////////////////////

 /*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE MCW_INSERT_OBSCLIN_VITAL_SIGNS_TOBACCO AS (
WITH MCW_vital_insert_wt AS (SELECT 
    NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	'29463-7' AS RAW_OBSCLIN_CODE,
	'LBS' AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	WT AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	NULL AS RAW_OBSCLIN_RESULT,
	'29463-7' AS OBSCLIN_CODE,
	'WT' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	'LBS' AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE WT IS NOT NULL ),

MCW_vital_insert_HT AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	'8302-2' AS RAW_OBSCLIN_CODE,
	'INCH(S)' AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	HT AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	NULL AS RAW_OBSCLIN_RESULT,
	'8302-2' AS OBSCLIN_CODE,
	'HT' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	'INCH(S)' AS OBSCLIN_RESULT_UNIT 
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE HT IS NOT NULL ),

MCW_vital_insert_BMI AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	'39156-5' AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	ORIGINAL_BMI AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	NULL AS RAW_OBSCLIN_RESULT,
	'39156-5' AS OBSCLIN_CODE,
	'BMI' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE ORIGINAL_BMI IS NOT NULL ),

MCW_vital_insert_DBP AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	'8462-4' AS RAW_OBSCLIN_CODE,
	'mmHg' AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	DIASTOLIC AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	NULL AS RAW_OBSCLIN_RESULT,
	'8462-2' AS OBSCLIN_CODE,
	'DIASTOLIC' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	'mmHg' AS OBSCLIN_RESULT_UNIT 
 FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE DIASTOLIC IS NOT NULL ),

MCW_vital_insert_SBP AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	'8480-6' AS RAW_OBSCLIN_CODE,
	'mmHg' AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	SYSTOLIC AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	NULL AS RAW_OBSCLIN_RESULT,
	'8480-6' AS OBSCLIN_CODE,
	'SYSTOLIC' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	'mmHg' AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE SYSTOLIC IS NOT NULL ),

MCW_vital_insert_smoking AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	SMOKING AS RAW_OBSCLIN_RESULT,
	NULL AS OBSCLIN_CODE,
	'SMOKING' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE  SMOKING != '' ),

MCW_vital_insert_TOBACCO AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	TOBACCO AS RAW_OBSCLIN_RESULT,
	NULL AS OBSCLIN_CODE,
	'TOBACCO' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE TOBACCO != ''  ),

MCW_vital_insert_TOBACCO_TYPE AS (SELECT 
    NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	TOBACCO_TYPE AS RAW_OBSCLIN_RESULT,
	NULL AS OBSCLIN_CODE,
	'TOBACCO_TYPE' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE TOBACCO_TYPE != '' )

SELECT * FROM MCW_vital_insert_WT
UNION
SELECT * FROM MCW_vital_insert_HT
UNION
SELECT * FROM MCW_vital_insert_BMI
UNION
SELECT * FROM MCW_vital_insert_DBP
UNION
SELECT * FROM MCW_vital_insert_SBP
UNION
SELECT * FROM MCW_VITAL_INSERT_SMOKING
UNION
SELECT * FROM MCW_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM MCW_VITAL_INSERT_TOBACCO_TYPE);


/*Create table for smoking data*/
CREATE OR REPLACE TABLE MCW_SMOKING_DATA AS (
WITH MCW_vital_insert_smoking AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	SMOKING AS RAW_OBSCLIN_RESULT,
	NULL AS OBSCLIN_CODE,
	'SMOKING' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE  SMOKING != '' ),

MCW_vital_insert_TOBACCO AS (SELECT 
	NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	TOBACCO AS RAW_OBSCLIN_RESULT,
	NULL AS OBSCLIN_CODE,
	'TOBACCO' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE TOBACCO != ''  ),

MCW_vital_insert_TOBACCO_TYPE AS (SELECT 
    NULL AS OBSCLINID ,
	NULL AS RAW_OBSCLIN_MODIFIER,
	NULL AS RAW_OBSCLIN_CODE,
	NULL AS RAW_OBSCLIN_UNIT,
	NULL AS OBSCLIN_SOURCE,
	ENCOUNTERID,
	MEASURE_TIME AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_RESULT_NUM ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	PATID,
	MEASURE_DATE AS OBSCLIN_STOP_DATE,
	NULL AS OBSCLIN_RESULT_QUAL,
	TOBACCO_TYPE AS RAW_OBSCLIN_RESULT,
	NULL AS OBSCLIN_CODE,
	'TOBACCO_TYPE' AS  RAW_OBSCLIN_NAME,
    MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_PROVIDERID,
	NULL AS OBSCLIN_RESULT_MODIFIER,
	NULL AS OBSCLIN_ABN_IND,
	NULL AS RAW_OBSCLIN_TYPE,
	NULL AS OBSCLIN_RESULT_SNOMED,
	NULL AS OBSCLIN_RESULT_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE TOBACCO_TYPE != '' )

SELECT * FROM MCW_VITAL_INSERT_SMOKING
UNION
SELECT * FROM MCW_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM MCW_VITAL_INSERT_TOBACCO_TYPE);

/*union both tables to create linke vital/obsclin table */
CREATE OR REPLACE TABLE MCW_linked_vital_obsclin AS
 
SELECT * FROM MCW_INSERT_OBSCLIN_VITAL_SIGNS_TOBACCO
UNION 
SELECT * FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_OBS_CLIN;



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////UIOWA////////////////////////////////////////////////////////////////////


---All vital data are already exist in obclin table
 /*Records of ht not exsit in OBSCLIN table*/
---all records in vital are already exist in obsclin
--CREATE OR REPLACE TABLE KUMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where HT is not null
MINUS ( SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN  B 
where obsclin_code = '3137-7');



/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_wt AS 
 SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where WT is not null
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN   B 
WHERE obsclin_code = '3141-9';
 

//*BMI*/
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where original_bmi is not null
MINUS (SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN   B 
where obsclin_code = '39156-5');


//*DBP*/

/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where diastolic is not null
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN  B 
where obsclin_code = '8480-6'
 ;

//*SBP*/

/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL  A 
where systolic is not null
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN  B 
where obsclin_code = '8462-4';


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////UNMC//////////////////////////////////////////////////////////////



 ---------------------------------
 /*Records of ht not exsit in OBSCLIN table*/
---all ht data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where HT is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where OBSCLIN_CODE  in ('8302-2','3137-7');


//*wt*/
 
/*create table for data in vital table not exists in obclin*/
---all wt data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where wt is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where obsclin_code in ('29463','3141-9') ;
 //


//*BMI*/
---all bmi data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where original_bmi is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where raw_obsclin_code = '39156-5';
//



//*DBP*/
/*check for different BMI names in obclin*/
---all dbp data  in vital are already exist in obsclin
---CREATE OR REPLACE TABLE UNMC_Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where diastolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where raw_obsclin_code = '8462-4';

//*SBP*/
/*create table for data in vital table not exists in obclin*/
---all sbp data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where systolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where raw_obsclin_code = '8480-6';



//////////////////////////////

/*Create table for smoking data*/
CREATE OR REPLACE TABLE UNMC_SMOKING_DATA AS (
WITH UNMC_vital_insert_smoking AS (SELECT
NULL AS OBSCLIN_TYPE ,
	NULL AS RAW_OBSCLIN_CODE ,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'SMOKING' AS RAW_OBSCLIN_NAME ,
	SMOKING AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_ABN_IND ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS OBSCLIN_PROVIDERID ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_CODE ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_MODIFIER ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLIN_RESULT_NUM ,
	ENCOUNTERID ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_STOP_DATE ,
	PATID 
	
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL
WHERE  SMOKING != '' ),

UNMC_vital_insert_TOBACCO AS (SELECT 
	NULL AS OBSCLIN_TYPE ,
	NULL AS RAW_OBSCLIN_CODE ,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'TOBACCO' AS RAW_OBSCLIN_NAME ,
	TOBACCO AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_ABN_IND ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS OBSCLIN_PROVIDERID ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_CODE ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_MODIFIER ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLIN_RESULT_NUM ,
	ENCOUNTERID ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_STOP_DATE ,
	PATID 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL
WHERE  TOBACCO != ''  ),

UNMC_vital_insert_TOBACCO_TYPE AS (SELECT 
    NULL AS OBSCLIN_TYPE ,
	NULL AS RAW_OBSCLIN_CODE ,
	MEASURE_TIME  AS OBSCLIN_START_TIME,
	'TOBACCO_TYPE' AS RAW_OBSCLIN_NAME ,
	TOBACCO_TYPE AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_ABN_IND ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS OBSCLIN_PROVIDERID ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_CODE ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_MODIFIER ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_UNIT ,
	NULL AS OBSCLIN_RESULT_NUM ,
	ENCOUNTERID ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_STOP_DATE ,
	PATID 
FROM GROUSE_DB.PCORNET_CDM_MCW.LDS_VITAL
WHERE   TOBACCO_TYPE != '' )

SELECT * FROM UNMC_VITAL_INSERT_SMOKING
UNION
SELECT * FROM UNMC_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM UNMC_VITAL_INSERT_TOBACCO_TYPE);

/*Modify colunm data type*/
create or replace table UNMC_Modified_INSERT_IN_OBC_SMOKING as

select 
 OBSCLIN_TYPE ,
 RAW_OBSCLIN_CODE ,
 OBSCLIN_START_TIME,
 RAW_OBSCLIN_NAME ,
 CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
 OBSCLIN_ABN_IND ,
 RAW_OBSCLIN_MODIFIER ,
 OBSCLIN_RESULT_UNIT ,
 OBSCLIN_PROVIDERID ,
 RAW_OBSCLIN_TYPE ,
 OBSCLIN_RESULT_SNOMED ,
 OBSCLIN_STOP_TIME ,
 OBSCLIN_CODE ,
 OBSCLINID ,
 OBSCLIN_RESULT_MODIFIER ,
 OBSCLIN_SOURCE ,
 RAW_OBSCLIN_UNIT ,
 CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
	ENCOUNTERID ,
 OBSCLIN_RESULT_QUAL ,
 OBSCLIN_START_DATE,
 OBSCLIN_RESULT_TEXT ,
 OBSCLIN_STOP_DATE ,
	PATID 

 

from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE. UNMC_SMOKING_DATA
;


/*The final linked table*/
create or replace table UNMC_linked_vital_obsclin_table as
SELECT * FROM UNMC_SMOKING_DATA
UNION
SELECT * FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN;
;


////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////UTHOUSTON/////////////////////////////////////////////////////////

 /*Records of ht not exsit in OBSCLIN table*/
--CREATE OR REPLACE TABLE UNMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A 
where HT is not null
MINUS SELECT b.patid, b.obsclin_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%height%');

 
 /*Create table for data exists in vital not obsclin*/
Create or replace table  UNMC_insert_obsc_ht as
 select a.* from GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UNMC_not_exsit_in_obslcin_ht b on b.patid = a.patid
 and b.encounterid = a.encounterid and b.MEASURE_DATE = a.measure_date and b.measure_time = a.measure_time;

//*wt*/
 
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_wt AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A 
where wt is not null
MINUS SELECT b.patid, b.obsclin_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%weight%');
 //



/*Create table for data exists in vital not obsclin*/
Create or replace table UTHOUSTON_insert_obsc_wt as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_wt b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;



//*BMI*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_bmi AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A 
where original_bmi is not null
MINUS SELECT b.patid, b.obsclin_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%bmi%');
//

/*create table for data in vital table not exists in obclin*/

/*Create table for data exists in vital not obsclin*/
Create or replace table UTHOUSTON_insert_obsc_bmi as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_bmi b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;


//*DBP*/
/*check for different BMI names in obclin*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_dbp AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A 
where diastolic is not null
MINUS SELECT b.patid, b.obsclin_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%diastolic%');



/*Create table for data exists in vital not obsclin*/

Create or replace table UTHOUSTON_insert_obsc_dbp as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_dbp b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;



//*SBP*/


/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_sbp AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A 
where systolic is not null
MINUS SELECT b.patid, b.obsclin_date
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%systolic%');



/*Create table for data exists in vital not obsclin*/
Create or replace table UTHOUSTON_insert_obsc_sbp as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_sbp b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;
//////////////////////////////
////////////////////////
/*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE UTHOUSTON_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH UTHOUSTON_vital_insert_BMI AS (SELECT     
   NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   NULL AS OBSCLIN_CODE,
   original_bmi AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   NULL AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   original_bmi as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   NULL AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   original_bmi AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'BMI' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_insert_obsc_bmi),

UTHOUSTON_vital_insert_DBP AS (SELECT 
	 NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   NULL AS OBSCLIN_CODE,
   DIASTOLIC AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   'mmHg' AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   DIASTOLIC as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   NULL AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   DIASTOLIC AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'DIASTOLIC' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_insert_obsc_dbp),

UTHOUSTON_vital_insert_SBP AS (SELECT 
	NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   NULL AS OBSCLIN_CODE,
   SYSTOLIC AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   'mmHg' AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   SYSTOLIC as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   NULL AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   SYSTOLIC AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'SYSTOLIC' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE

   
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_insert_obsc_Sbp)


SELECT * FROM UTHOUSTON_vital_insert_BMI
UNION
SELECT * FROM UTHOUSTON_vital_insert_DBP
UNION
SELECT * FROM UTHOUSTON_vital_insert_SBP
);
------
 

/*Modify colunm data type*/
create or replace table UTHOUSTON_Modified_INSERT_IN_OBC_ALL as

select 
 
OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
	OBSCLIN_CODE,
	CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT ,
	OBSCLIN_DATE ,
	OBSCLIN_TYPE ,
	OBSCLIN_PROVIDERID ,
	OBSCLIN_RESULT_UNIT ,
	OBSCLIN_RESULT_QUAL ,
	RAW_OBSCLIN_MODIFIER ,
	OBSCLIN_RESULT_MODIFIER,
	OBSCLINID ,
	PATID ,
	OBSCLIN_SOURCE ,
	RAW_OBSCLIN_TYPE ,
	CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM ,
	OBSCLIN_START_TIME ,
	OBSCLIN_ABN_IND ,
	RAW_OBSCLIN_CODE ,
	OBSCLIN_TIME ,
    CAST( OBSCLIN_RESULT_TEXT AS VARCHAR(200))AS OBSCLIN_RESULT_TEXT,
	OBSCLIN_START_DATE ,
	RAW_OBSCLIN_UNIT ,
	RAW_OBSCLIN_NAME ,
	OBSCLIN_STOP_TIME ,
	OBSCLIN_STOP_DATE 
 

from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_INSERT_OBSCLIN_VITAL_SIGNS
;

/*LINKE TO MAIN OBSCLIN TABLE */
CREATE OR REPLACE TABLE UTHOUSTON_LINKED_VITAL_OBSCLIN AS
SELECT * FROM UTHOUSTON_Modified_INSERT_IN_OBC_ALL
UNION
SELECT * FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.LDS_OBS_CLIN;
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////UTHSCSA///////////////////////////////////////////////////////////////////////
/*vital inserted to obsclin */
CREATE OR REPLACE TABLE UTHSCSA_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH UTHSCSA_vital_insert_HT AS (SELECT     
   NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   '8302-2' AS OBSCLIN_CODE,
   HT AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   'INCH(S)' AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   HT as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   '8302-2' AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL  AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   'INCH(S)' AS RAW_OBSCLIN_UNIT ,
   'HT' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
where ht is not null),

UTHSCSA_vital_insert_WT AS (SELECT     
   NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   '29463-7' AS OBSCLIN_CODE,
   WT AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   'LBS' AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   WT as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   '29463-7' AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   'LBS' AS RAW_OBSCLIN_UNIT ,
   'WT' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
where wt is not null ),

UTHSCSA_vital_insert_BMI AS (SELECT     
   NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   '39156-5' AS OBSCLIN_CODE,
   original_bmi AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   NULL AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   original_bmi as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   '39156-5' AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'BMI' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
where original_bmi is not null ),

UTHSCSA_vital_insert_DBP AS (SELECT 
	 NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   '8462-4' AS OBSCLIN_CODE,
   DIASTOLIC AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   'mmHg' AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   DIASTOLIC as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   '8462-4' AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   'mmHg' AS RAW_OBSCLIN_UNIT ,
   'DIASTOLIC' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE

FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
where diastolic is not null ),

UTHSCSA_vital_insert_SBP AS (SELECT 
	NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   '8480-6' AS OBSCLIN_CODE,
   SYSTOLIC AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   'mmHg' AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   SYSTOLIC as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   '8480-6' AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   'mmHg' AS RAW_OBSCLIN_UNIT ,
   'SYSTOLIC' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE

   
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
where systolic is not null )



SELECT * FROM UTHSCSA_vital_insert_ht
union
SELECT * FROM UTHSCSA_vital_insert_wt
union
SELECT * FROM UTHSCSA_vital_insert_BMI
UNION
SELECT * FROM UTHSCSA_vital_insert_DBP
UNION
SELECT * FROM UTHSCSA_vital_insert_SBP

);


/*Modify colunm data type*/
create or replace table UTHSCSA_Modified_INSERT_IN_OBC_ALL as

select 
 
 OBSCLIN_RESULT_SNOMED ,
 ENCOUNTERID,
 OBSCLIN_CODE,
 CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
 OBSCLIN_DATE ,
 OBSCLIN_TYPE ,
 OBSCLIN_PROVIDERID ,
 OBSCLIN_RESULT_UNIT ,
 OBSCLIN_RESULT_QUAL ,
 RAW_OBSCLIN_MODIFIER ,
 OBSCLIN_RESULT_MODIFIER,
 OBSCLINID ,
	PATID ,
 OBSCLIN_SOURCE ,
 RAW_OBSCLIN_TYPE ,
 CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
 OBSCLIN_START_TIME ,
 OBSCLIN_ABN_IND ,
 RAW_OBSCLIN_CODE ,
 OBSCLIN_TIME ,
 OBSCLIN_RESULT_TEXT ,
 OBSCLIN_START_DATE ,
 RAW_OBSCLIN_UNIT ,
 RAW_OBSCLIN_NAME ,
 OBSCLIN_STOP_TIME ,
 OBSCLIN_STOP_DATE


from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHSCSA_INSERT_OBSCLIN_VITAL_SIGNS
;

/*SMOKING DATA */
CREATE OR REPLACE TABLE UTHSCSA_SMOKING_DATA AS 
WITH UTHSCSA_vital_insert_smoking AS (SELECT
NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   NULL AS OBSCLIN_CODE,
   SMOKING AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   NULL AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   smoking as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   NULL AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'smoking' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
WHERE  SMOKING != '' ),

UTHSCSA_vital_insert_TOBACCO AS (SELECT 
	NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   NULL AS OBSCLIN_CODE,
   TOBACCO AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   NULL AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   tobacco as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   NULL AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'TOBACCO' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
WHERE  TOBACCO != ''  ),

UTHSCSA_vital_insert_TOBACCO_TYPE AS (SELECT 
    NULL AS  OBSCLIN_RESULT_SNOMED ,
	ENCOUNTERID,
   NULL AS OBSCLIN_CODE,
   TOBACCO_TYPE AS  RAW_OBSCLIN_RESULT ,
   MEASURE_DATE AS  OBSCLIN_DATE ,
   NULL AS OBSCLIN_TYPE ,
   NULL AS OBSCLIN_PROVIDERID ,
   NULL AS OBSCLIN_RESULT_UNIT ,
   NULL AS OBSCLIN_RESULT_QUAL ,
   NULL AS RAW_OBSCLIN_MODIFIER ,
   NULL AS OBSCLIN_RESULT_MODIFIER,
   NULL AS OBSCLINID ,
	PATID ,
   NULL AS OBSCLIN_SOURCE ,
   NULL AS RAW_OBSCLIN_TYPE ,
   TOBACCO_TYPE as OBSCLIN_RESULT_NUM ,
   MEASURE_TIME AS OBSCLIN_START_TIME ,
   NULL AS OBSCLIN_ABN_IND ,
   NULL AS RAW_OBSCLIN_CODE ,
   MEASURE_TIME AS OBSCLIN_TIME ,
   NULL AS OBSCLIN_RESULT_TEXT ,
   MEASURE_DATE AS OBSCLIN_START_DATE ,
   NULL AS RAW_OBSCLIN_UNIT ,
   'TOBACCO_TYPE' AS RAW_OBSCLIN_NAME ,
   NULL AS OBSCLIN_STOP_TIME ,
   NULL AS OBSCLIN_STOP_DATE 
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.LDS_VITAL
WHERE   TOBACCO_TYPE != '' )

SELECT * FROM UTHSCSA_VITAL_INSERT_SMOKING
UNION
SELECT * FROM UTHSCSA_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM UTHSCSA_VITAL_INSERT_TOBACCO_TYPE;

/*LINKED VITALA AND OBSCLIN*/
create or replace table UTHSCSA_linked_vital_obsclin as 
SELECT * FROM UTHSCSA_Modified_INSERT_IN_OBC_ALL
UNION
SELECT * FROM UTHSCSA_SMOKING_DATA;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////UTSW////////////////////////////////////////////////////////////////////////////

 /*Records of ht not exsit in OBSCLIN table*/
---all records in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UTSW_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where HT is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN  B 
where OBSCLIN_CODE = '8302-2';

//*wt*/
 
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE UTSW_not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL  A 
where wt is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN   B 
where OBSCLIN_CODE in ('29463-7' ,'3141-9') ;
 

//*BMI*/
--CREATE OR REPLACE TABLE UNMC_not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where original_bmi is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN  B 
where OBSCLIN_CODE = '39156-5';
//


//*DBP*/
/*check for different BMI names in obclin*/
--CREATE OR REPLACE TABLE UNMC_Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where diastolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN   B 
where obsclin_code = '8462-4';


//*SBP*/


/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE UNMC_Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where systolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN  B 
where obsclin_code = '8480-6';


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////UU//////////////////////////////////////////////////////////////////////

/*Records of ht not exsit in OBSCLIN table*/

CREATE OR REPLACE TABLE UU_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date 
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL  A 
where HT is not null
MINUS  SELECT b.patid, b.obsclin_start_date
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_OBS_CLIN  B 
where OBSCLIN_CODE in ('8302-2','3137-7') ;


/*Create table for data exists in vital not obsclin*/
Create or replace table  UU_insert_obsc_HT as
 select a.* from GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UU_not_exsit_in_obslcin_ht b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;
 

//*wt*/
 
/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE UU_not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL  A 
where wt is not null
MINUS  SELECT b.patid, b.obsclin_start_date
FROM  GROUSE_DB.PCORNET_CDM_UU.LDS_OBS_CLIN  B 
where OBSCLIN_CODE in ('29463-7', '3141-9') ;


/*Create table for data exists in vital not obsclin*/
Create or replace table  UU_insert_obsc_wt as
 select a.* from GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL A
 join grouse_db_quail.dq_clean_table.UU_not_exists_in_obsclin_wt b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;

/*Transform vital table to obclin*/
CREATE OR REPLACE TABLE UU_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH UU_vital_insert_HT AS (SELECT     
   ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	'INCH(S)' AS RAW_OBSCLIN_UNIT,
	'HT' AS RAW_OBSCLIN_NAME ,
	'8302-2' RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	HT AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	'INCH(S)' AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	'8302-2' AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	HT AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND  
FROM grouse_db_quail.dq_clean_table.UU_insert_obsc_HT),

UU_vital_insert_WT AS (SELECT     
   ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	'LBS' AS RAW_OBSCLIN_UNIT,
	'WT' AS RAW_OBSCLIN_NAME ,
	'29463-7' RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	WT AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	'LBS' AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	'29463-7' AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	WT AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND 
FROM grouse_db_quail.dq_clean_table.UU_insert_obsc_wt
 ),

UU_vital_insert_BMI AS (SELECT     
   ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	NULL AS RAW_OBSCLIN_UNIT,
	'BMI' AS RAW_OBSCLIN_NAME ,
	'39156-5' RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	ORIGINAL_BMI AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	'39156-5' AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	ORIGINAL_BMI AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL
where original_bmi is not null ),

UU_vital_insert_DBP AS (SELECT 
	 ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	'mmHg' AS RAW_OBSCLIN_UNIT,
	'DBP' AS RAW_OBSCLIN_NAME ,
	'8462-4' RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	DIASTOLIC AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	'mmHg' AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	'8462-4' AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	DIASTOLIC AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND

FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL
where diastolic is not null ),

UU_vital_insert_SBP AS (SELECT 
	ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	'mmHg' AS RAW_OBSCLIN_UNIT,
	'SBP' AS RAW_OBSCLIN_NAME ,
	'8480-6' RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	SYSTOLIC  AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	'mmHg' AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	'8480-6' AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	SYSTOLIC AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND
   
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL
where systolic is not null )



SELECT * FROM UU_vital_insert_ht
union
SELECT * FROM UU_vital_insert_wt
union
SELECT * FROM UU_vital_insert_BMI
UNION
SELECT * FROM UU_vital_insert_DBP
UNION
SELECT * FROM UU_vital_insert_SBP

);



/*Modify colunm data type*/
create or replace table UU_Modified_INSERT_IN_OBC_ALL as

select 
 
ENCOUNTERID ,
	OBSCLIN_RESULT_MODIFIER ,
	RAW_OBSCLIN_UNIT,
	RAW_OBSCLIN_NAME ,
	RAW_OBSCLIN_CODE ,
	OBSCLIN_RESULT_TEXT ,
	OBSCLIN_RESULT_SNOMED ,
	OBSCLIN_RESULT_QUAL ,
	 CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
	OBSCLINID ,
	OBSCLIN_RESULT_UNIT ,
	RAW_OBSCLIN_MODIFIER ,
	OBSCLIN_START_TIME,
	OBSCLIN_CODE ,
	OBSCLIN_TYPE ,
	OBSCLIN_START_DATE,
	PATID ,
	OBSCLIN_SOURCE ,
	RAW_OBSCLIN_TYPE ,
	OBSCLIN_PROVIDERID ,
	CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT ,
	OBSCLIN_STOP_TIME ,
	OBSCLIN_STOP_DATE ,
	OBSCLIN_ABN_IND 
from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UU_INSERT_OBSCLIN_VITAL_SIGNS
;

/*SMOKING DATA */
CREATE OR REPLACE TABLE UU_SMOKING_DATA AS 
WITH UU_vital_insert_smoking AS (SELECT
ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	NULL AS RAW_OBSCLIN_UNIT,
	'SMOKING' AS RAW_OBSCLIN_NAME ,
	NULL AS  RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	SMOKING  AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	NULL AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	SMOKING AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND
   
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL
WHERE  SMOKING NOT IN ('','NI') ),

UU_vital_insert_TOBACCO AS (SELECT 
	ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	NULL AS RAW_OBSCLIN_UNIT,
	'TOBACCO' AS RAW_OBSCLIN_NAME ,
	NULL AS  RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	TOBACCO  AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	NULL AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	TOBACCO AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL
WHERE  TOBACCO NOT IN ('','NI')  ),

UU_vital_insert_TOBACCO_TYPE AS (SELECT 
   ENCOUNTERID ,
	NULL AS  OBSCLIN_RESULT_MODIFIER ,
	NULL AS RAW_OBSCLIN_UNIT,
	'TOBACCO_TYPE' AS RAW_OBSCLIN_NAME ,
	NULL AS  RAW_OBSCLIN_CODE ,
	NULL AS OBSCLIN_RESULT_TEXT ,
	NULL AS OBSCLIN_RESULT_SNOMED ,
	NULL AS OBSCLIN_RESULT_QUAL ,
	TOBACCO_TYPE  AS OBSCLIN_RESULT_NUM ,
	NULL AS OBSCLINID ,
	NULL AS OBSCLIN_RESULT_UNIT ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	MEASURE_TIME AS OBSCLIN_START_TIME,
	NULL AS OBSCLIN_CODE ,
	NULL AS OBSCLIN_TYPE ,
	MEASURE_DATE AS OBSCLIN_START_DATE,
	PATID ,
	NULL AS OBSCLIN_SOURCE ,
	NULL AS RAW_OBSCLIN_TYPE ,
	NULL AS OBSCLIN_PROVIDERID ,
	TOBACCO_TYPE AS RAW_OBSCLIN_RESULT ,
	NULL AS OBSCLIN_STOP_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS OBSCLIN_ABN_IND
FROM GROUSE_DB.PCORNET_CDM_UU.LDS_VITAL
WHERE   TOBACCO_TYPE NOT IN ('','NI') )

SELECT * FROM UU_VITAL_INSERT_SMOKING
UNION
SELECT * FROM UU_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM UU_VITAL_INSERT_TOBACCO_TYPE;


/*LINKED VITALA AND OBSCLIN*/
create or replace table UU_LINKED_VITAL_OBSCLIN as 
SELECT * FROM UU_Modified_INSERT_IN_OBC_ALL
UNION
SELECT * FROM UU_SMOKING_DATA
UNION 
SELECT* FROM GROUSE_DB.PCORNET_CDM_UU.LDS_OBS_CLIN
;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////WAHSU/////////////////////////////////////////////////////////////////////////

-----
/*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE WHASHU_OBSCLIN_VITAL AS (
WITH WHASHU_vital_insert_HT AS (SELECT     
    NULL AS OBSCLIN_SOURCE ,
   '8302-2' AS RAW_OBSCLIN_CODE ,
   'HT' AS RAW_OBSCLIN_NAME ,
   'INCH(S)' AS OBSCLIN_RESULT_UNIT ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_PROVIDERID ,
   '8302-2' AS OBSCLIN_CODE ,
    NULL AS OBSCLIN_RESULT_QUAL ,
    NULL AS	OBSCLIN_RESULT_SNOMED ,
   'INCH(S)' AS RAW_OBSCLIN_UNIT ,
    NULL AS	OBSCLINID ,
	PATID ,
    NULL AS	OBSCLIN_TYPE,
    NULL AS	OBSCLIN_STOP_TIME ,
	ENCOUNTERID ,
	HT AS RAW_OBSCLIN_RESULT,
    NULL AS	OBSCLIN_RESULT_MODIFIER ,
    NULL AS	OBSCLIN_RESULT_TEXT ,
	HT AS OBSCLIN_RESULT_NUM ,
    NULL AS	OBSCLIN_ABN_IND ,
 	MEASURE_DATE AS OBSCLIN_START_DATE ,
    NULL AS	RAW_OBSCLIN_TYPE 
FROM GROUSE_DB.PCORNET_CDM_WASHU.LDS_VITAL
where ht is not null),

WHASHU_vital_insert_WT AS (SELECT     
    NULL AS OBSCLIN_SOURCE ,
   '29463-7' AS RAW_OBSCLIN_CODE ,
   'WT' AS RAW_OBSCLIN_NAME ,
   'LBS' AS OBSCLIN_RESULT_UNIT ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_PROVIDERID ,
   '29463-7' AS OBSCLIN_CODE ,
    NULL AS OBSCLIN_RESULT_QUAL ,
    NULL AS	OBSCLIN_RESULT_SNOMED ,
   'LBS' AS RAW_OBSCLIN_UNIT ,
    NULL AS	OBSCLINID ,
	PATID ,
    NULL AS	OBSCLIN_TYPE,
    NULL AS	OBSCLIN_STOP_TIME ,
	ENCOUNTERID ,
	WT AS RAW_OBSCLIN_RESULT,
    NULL AS	OBSCLIN_RESULT_MODIFIER ,
    NULL AS	OBSCLIN_RESULT_TEXT ,
	WT AS OBSCLIN_RESULT_NUM ,
    NULL AS	OBSCLIN_ABN_IND ,
 	MEASURE_DATE AS OBSCLIN_START_DATE ,
    NULL AS	RAW_OBSCLIN_TYPE 
FROM GROUSE_DB.PCORNET_CDM_WASHU.LDS_VITAL
where wt is not null ),

WHASHU_vital_insert_BMI AS (SELECT     
    NULL AS OBSCLIN_SOURCE ,
   '39156-5' AS RAW_OBSCLIN_CODE ,
   'BMI' AS RAW_OBSCLIN_NAME ,
    NULL AS OBSCLIN_RESULT_UNIT ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_PROVIDERID ,
   '39156-5' AS OBSCLIN_CODE ,
    NULL AS OBSCLIN_RESULT_QUAL ,
    NULL AS	OBSCLIN_RESULT_SNOMED ,
    NULL AS RAW_OBSCLIN_UNIT ,
    NULL AS	OBSCLINID ,
	PATID ,
    NULL AS	OBSCLIN_TYPE,
    NULL AS	OBSCLIN_STOP_TIME ,
	ENCOUNTERID ,
	ORIGINAL_BMI AS RAW_OBSCLIN_RESULT,
    NULL AS	OBSCLIN_RESULT_MODIFIER ,
    NULL AS	OBSCLIN_RESULT_TEXT ,
	ORIGINAL_BMI AS OBSCLIN_RESULT_NUM ,
    NULL AS	OBSCLIN_ABN_IND ,
 	MEASURE_DATE AS OBSCLIN_START_DATE ,
    NULL AS	RAW_OBSCLIN_TYPE 
FROM GROUSE_DB.PCORNET_CDM_WASHU.LDS_VITAL
where original_bmi is not null ),

WHASHU_vital_insert_DBP AS (SELECT 
	 NULL AS OBSCLIN_SOURCE ,
   '8462-5' AS RAW_OBSCLIN_CODE ,
   'DBP' AS RAW_OBSCLIN_NAME ,
    'mmHg' AS OBSCLIN_RESULT_UNIT ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_PROVIDERID ,
   '8462-5' AS OBSCLIN_CODE ,
    NULL AS OBSCLIN_RESULT_QUAL ,
    NULL AS	OBSCLIN_RESULT_SNOMED ,
    'mmHg' AS RAW_OBSCLIN_UNIT ,
    NULL AS	OBSCLINID ,
	PATID ,
    NULL AS	OBSCLIN_TYPE,
    NULL AS	OBSCLIN_STOP_TIME ,
	ENCOUNTERID ,
	DIASTOLIC AS RAW_OBSCLIN_RESULT,
    NULL AS	OBSCLIN_RESULT_MODIFIER ,
    NULL AS	OBSCLIN_RESULT_TEXT ,
	DIASTOLIC AS OBSCLIN_RESULT_NUM ,
    NULL AS	OBSCLIN_ABN_IND ,
 	MEASURE_DATE AS OBSCLIN_START_DATE ,
    NULL AS	RAW_OBSCLIN_TYPE

FROM GROUSE_DB.PCORNET_CDM_WASHU.LDS_VITAL
where diastolic is not null ),

WHASHU_vital_insert_SBP AS (SELECT 
	 NULL AS OBSCLIN_SOURCE ,
   '8480-6' AS RAW_OBSCLIN_CODE ,
   'SBP' AS RAW_OBSCLIN_NAME ,
    'mmHg' AS OBSCLIN_RESULT_UNIT ,
	MEASURE_TIME AS OBSCLIN_START_TIME ,
	NULL AS OBSCLIN_STOP_DATE ,
	NULL AS RAW_OBSCLIN_MODIFIER ,
	NULL AS OBSCLIN_PROVIDERID ,
   '8480-6' AS OBSCLIN_CODE ,
    NULL AS OBSCLIN_RESULT_QUAL ,
    NULL AS	OBSCLIN_RESULT_SNOMED ,
    'mmHg' AS RAW_OBSCLIN_UNIT ,
    NULL AS	OBSCLINID ,
	PATID ,
    NULL AS	OBSCLIN_TYPE,
    NULL AS	OBSCLIN_STOP_TIME ,
	ENCOUNTERID ,
	systolic AS RAW_OBSCLIN_RESULT,
    NULL AS	OBSCLIN_RESULT_MODIFIER ,
    NULL AS	OBSCLIN_RESULT_TEXT ,
	systolic AS OBSCLIN_RESULT_NUM ,
    NULL AS	OBSCLIN_ABN_IND ,
 	MEASURE_DATE AS OBSCLIN_START_DATE ,
    NULL AS	RAW_OBSCLIN_TYPE
   
FROM GROUSE_DB.PCORNET_CDM_WASHU.LDS_VITAL
where systolic is not null )



SELECT * FROM WHASHU_vital_insert_ht
union
SELECT * FROM WHASHU_vital_insert_wt
union
SELECT * FROM WHASHU_vital_insert_BMI
UNION
SELECT * FROM WHASHU_vital_insert_DBP
UNION
SELECT * FROM WHASHU_vital_insert_SBP

);



