/*Vital table tranformation to obliclin table for all sites*/

/*Transforme vital table to obsclin MU data*/



SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'height (cm)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (feet)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (inches)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length measured%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (inches calc)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length estimated%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length dosing%');

/*Records of height not exsit in OBSCLIN table*/

--CREATE OR replace TABLE not_exsit_in_obslcin_ht as
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A 
WHERE HT  IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'height (cm)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (feet)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (inches)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length measured%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height (inches calc)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length estimated%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'height/length dosing%');

/*Create table for data exists in vital not obsclin*/
CREATE OR REPLACE TABLE   insert_obsc_ht AS
SELECT a.* FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A
 JOIN grouse_db_quail.dq_clean_table.not_exsit_in_obslcin_ht b ON b.patid = a.patid
 AND b.encounterid = a.encounterid AND b.measure_date = a.measure_date AND b.measure_time = a.measure_time;

/*Records of weight not exsit in OBSCLIN table*/
 
/*create table for wt data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A 
WHERE WT IS NOT NULL
MINUS SELECT b.patid, b.obsclin_stop_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'weight (lbs calc)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight (kg)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight (lbs)%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight measured%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight for height/length percentile%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight percentile%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight estimated%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'weight-dialysis%');

 /*Create table for data exists in vital not obsclin WT*/
CREATE OR REPLACE TABLE  insert_obsc_wt AS
SELECT  a.* FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A
JOIN grouse_db_quail.dq_clean_table.Not_exists_in_obsclin_wt b ON  b.patid = a.patid
AND  b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;

 /*Records of BMI not exsit in OBSCLIN table*/ 

/*create table for bmi data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A 
WHERE original_bmi  IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN  B 
WHERE  (lower (b.RAW_OBSCLIN_NAME) LIKE  'bmi%'
 OR lower (b.RAW_OBSCLIN_NAME) LIKE  'bmi percentile%'
);

/*Create table for data exists in vital not obsclin*/
CREATE OR REPLACE TABLE  insert_obsc_bmi AS
SELECT  a.* FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A
JOIN grouse_db_quail.dq_clean_table.Not_exists_in_obsclin_bmi b ON  b.patid = a.patid
AND  b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;


/*Records of daistolic blood prossure (DBP) not exsit in OBSCLIN table*/  

/*create table for dbp data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A 
WHERE  diastolic IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%diastolic%'
OR upper (raw_obsclin_name) LIKE '%dbp%'
);

/*Create table for data exists in vital not obsclin*/
Create OR REPLACE TABLE   insert_obsc_dbp AS
SELECT a.* FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A
JOIN grouse_db_quail.dq_clean_table.NOT_EXISTS_IN_OBSCLIN_DBP b ON b.patid = a.patid
AND b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;

/*Records of systolic blood prossure (SBP) not exsit in OBSCLIN table*/

/*create table for sbp data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A 
WHERE  systolic IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN  B 
WHERE  (lower (raw_obsclin_name) LIKE '%systolic%'
 or upper (raw_obsclin_name) LIKE '%sbp%'
); 

/*Create table for data exists in vital not obsclin sbp*/
Create OR REPLACE TABLE   insert_obsc_dbp AS
SELECT a.* FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_VITAL A
JOIN grouse_db_quail.dq_clean_table.NOT_EXISTS_IN_OBSCLIN_SBP b ON b.patid = a.patid
AND b.encounterid = a.encounterid AND b.MEASURE_DATE = a.measure_date AND b.measure_time = a.measure_time;

/*Create table for data exists in vital not obsclin*/
CREATE OR REPLACE TABLE MU_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH MU_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.insert_obsc_wt),


MU_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_HT),

MU_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_BMI),

MU_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_DBP),

MU_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.INSERT_OBSC_SBP)

SELECT * FROM MU_vital_insert_WT
UNION
SELECT * FROM MU_vital_insert_HT
UNION
SELECT * FROM MU_vital_insert_BMI
UNION
SELECT * FROM MU_vital_insert_DBP
UNION
SELECT * FROM MU_vital_insert_SBP);



/*Modify colunm data type*/
CREATE OR REPLACE TABLE Modified_INSERT_IN_OBC_ALL AS

SELECT 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MU_INSERT_OBSCLIN_VITAL_SIGNS
;


----
;;

/*The final linked table*/
create or replace table Mu_linked_vital_obsclin_table as
SELECT * FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.Modified_INSERT_IN_OBC_ALL
UNION 
SELECT * FROM GROUSE_DB.PCORNET_CDM_MU.V_DEID_OBS_CLIN;



////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////ALLINA////////////////////////////////////////////////////////////


 /*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE ALLINA_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH MU_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE WT IS NOT NULL ),


MU_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE HT IS NOT NULL),

MU_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE original_bmi IS NOT NULL),

MU_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE diastolic IS NOT NULL),

MU_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE systolic IS NOT NULL

 )

SELECT * FROM ALLINA_vital_insert_WT
UNION
SELECT * FROM ALLINA_vital_insert_HT
UNION
SELECT * FROM ALLINA_vital_insert_BMI
UNION
SELECT * FROM ALLINA_vital_insert_DBP
UNION
SELECT * FROM ALLINA_vital_insert_SBP);

 -----
/*Create table for smoking data*/
CREATE OR REPLACE TABLE ALLINA_SMOKING_DATA AS (
WITH ALLINA_vital_insert_smoking AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
smoking  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'smoking' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
smoking AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE smoking NOT IN ('NULL', 'OT','NI','')

 ),

ALLINA_vital_insert_TOBACCO AS (SELECT 

NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE tobacco NOT IN ('NULL', 'OT','NI','')
  ),

ALLINA_vital_insert_TOBACCO_TYPE AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco_type  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco_type' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco_type AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
WHERE tobacco_type NOT IN ('NULL', 'OT','NI','')

 )

SELECT * FROM ALLINA_VITAL_INSERT_SMOKING
UNION
SELECT * FROM ALLINA_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM ALLINA_VITAL_INSERT_TOBACCO_TYPE);



/*Modify colunm data type*/
CREATE OR REPLACE TABLE Modified_allina_INSERT_IN_OBC_vital AS

SELECT 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.ALLINA_INSERT_OBSCLIN_VITAL_SIGNS
;


/*Modify colunm data type*/
CREATE OR REPLACE TABLE  Modified_allina_INSERT_IN_OBC_tobacoo AS

SELECT 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
CAST( OBSCLIN_RESULT_QUAL AS VARCHAR(200))AS OBSCLIN_RESULT_QUAL,
CAST( OBSCLIN_RESULT_TEXT AS VARCHAR(200))AS OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.ALLINA_SMOKING_DATA
;
-------------------------------------
-------------------------------------
/*union both tables */
create or replace table Allina_linked_vital_obsclin as 
select * from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.Modified_allina_INSERT_IN_OBC_tobacoo
union
select * from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.Modified_allina_INSERT_IN_OBC_vital
union
select * from GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_OBS_CLIN;

;


select * from GROUSE_DB.PCORNET_CDM_ALLINA.V_DEID_VITAL
where smoking like ('%OT%');



////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////IHC////////////////////////////////////////////////////////////


 /*vital Wt inserted to obsclin */

CREATE OR REPLACE TABLE IHC_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH HT_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_IHC.V_DEID_VITAL
WHERE WT IS NOT NULL ),


HT_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_IHC.V_DEID_VITAL
WHERE HT IS NOT NULL),

HT_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_IHC.V_DEID_VITAL
WHERE original_bmi IS NOT NULL),

HT_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_IHC.V_DEID_VITAL
WHERE diastolic IS NOT NULL),

HT_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_IHC.V_DEID_VITAL
WHERE systolic IS NOT NULL )

SELECT * FROM IHC_vital_insert_WT
UNION
SELECT * FROM IHC_vital_insert_HT
UNION
SELECT * FROM IHC_vital_insert_BMI
UNION
SELECT * FROM IHC_vital_insert_DBP
UNION
SELECT * FROM IHC_vital_insert_SBP);

 ------------------------------------




/*Modify colunm data type*/
CREATE OR REPLACE TABLE Modified_ihc_INSERT_IN_OBC_ALL AS

SELECT
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT

FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.IHC_INSERT_OBSCLIN_VITAL_SIGNS
;


/*The final linked table*/
create or replace table linked_ihc_vital_obsclin_table as
SELECT *
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MODIFIED_ihc_INSERT_IN_OBC_ALL
UNION 
SELECT *  FROM GROUSE_DB.PCORNET_CDM_IHC.V_DEID_OBS_CLIN;
;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////KUMC////////////////////////////////////////////////////////////////////////

---All vital data alrady exist in obclin table
/*Records of ht not exsit in OBSCLIN table*/
---all records in vital are already exist in obsclin
--CREATE OR REPLACE TABLE KUMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE HT IS NOT NULL
MINUS ( SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'ht%'
 ));
  
//*wt*/

 
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE WT IS NOT NULL
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (b.RAW_OBSCLIN_NAME) LIKE  'wt%'
 );

//*BMI*/


/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE original_bmi IS NOT NULL
MINUS (SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE  (lower (b.RAW_OBSCLIN_NAME) LIKE  '%bmi%'
 
));

//*DBP*/

 
/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL A 
WHERE  diastolic IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%diastolic%'
 
);


//*SBP*/

/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE  systolic IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%systolic%'
 
); 

//*smoking*/



/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE  smoking IS NOT NULL  
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%smoking%'
 
); 


//*tobacco*/


/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE tobacco IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE (lower (raw_obsclin_name) LIKE '%tobacco'
 
); 

//*tobacco_type*/


/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_VITAL  A 
WHERE  tobacco_type  IS NOT NULL 
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN  B 
WHERE  (lower (raw_obsclin_name) LIKE  'tobacco_type'
 
); 
/*Create table to make the result values in obsclin_result_num&raw_obsclin_results colunms*/
Create or replace table linked_kumc_obsclin as 
select OBSCLIN_RESULT_UNIT ,
	OBSCLIN_SOURCE ,
	OBSCLIN_TYPE ,
	OBSCLIN_START_DATE ,
	OBSCLIN_STOP_TIME ,
	OBSCLINID ,
	OBSCLIN_START_TIME ,
	OBSCLIN_CODE ,
	PATID ,
	RAW_OBSCLIN_UNIT ,
	OBSCLIN_PROVIDERID ,
	OBSCLIN_STOP_DATE ,
	OBSCLIN_RESULT_SNOMED ,
	RAW_OBSCLIN_TYPE ,
	ENCOUNTERID ,
obsclin_result_text AS	RAW_OBSCLIN_RESULT ,
	RAW_OBSCLIN_NAME ,
obsclin_result_text AS OBSCLIN_RESULT_NUM ,
	RAW_OBSCLIN_CODE ,
NULL AS	OBSCLIN_RESULT_TEXT ,
	RAW_OBSCLIN_MODIFIER ,
	OBSCLIN_RESULT_MODIFIER ,
	OBSCLIN_ABN_IND ,
	OBSCLIN_RESULT_QUAL 
    From GROUSE_DB.PCORNET_CDM_KUMC.LDS_OBS_CLIN;
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////MRCI////////////////////////////////////////////////////////////////
/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE MCRI_Not_exists_in_obsclin_all AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM  GROUSE_DB.PCORNET_CDM_MCRI.V_DEID_VITAL A 

MINUS (SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM  GROUSE_DB.PCORNET_CDM_MCRI.V_DEID_OBS_CLIN B )

 
; 


/*Create table for data exists in vital not obsclin*/
Create or replace table  mcri_insert_obsclin as
 select distinct a.* from GROUSE_DB.PCORNET_CDM_MCRI.V_DEID_VITAL  A
 join grouse_db_quail.dq_clean_table.mcri_not_exists_in_obsclin_all b on b.patid = a.patid
 and b.encounterid = a.encounterid and b.MEASURE_DATE = a.measure_date and b.measure_time = a.measure_time;


/*vital sings nserted to obsclin*/


CREATE OR REPLACE TABLE  MCRI_vital_SINGS AS (
WITH  MCRI_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE WT IS NOT NULL ),


Mcri_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE HT IS NOT NULL),

Mcri_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE original_bmi IS NOT NULL),

Mcri_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE diastolic IS NOT NULL),

Mcri_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE systolic IS NOT NULL 

)


SELECT * FROM MCRI_vital_insert_WT
UNION
SELECT * FROM MCRI_vital_insert_HT
UNION
SELECT * FROM MCRI_vital_insert_BMI
UNION
SELECT * FROM MCRI_vital_insert_DBP
UNION
SELECT * FROM MCRI_vital_insert_SBP

)


;
-------
/*Create table for smoking data*/
CREATE OR REPLACE TABLE MCRI_SMOKING_DATA AS (
WITH MRCI_vital_insert_smoking AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
smoking  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'smoking' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
smoking AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE smoking NOT IN ('NULL', 'OT','NI','','UN')

 ),

MRCI_vital_insert_TOBACCO AS (SELECT 

NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE tobacco NOT IN ('NULL', 'OT','NI','','UN')
  ),

MRCI_vital_insert_TOBACCO_TYPE AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco_type  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco_type' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco_type AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.mcri_insert_obsclin
WHERE tobacco_type NOT IN ('NULL', 'OT','NI','','UN')

)
SELECT * FROM MRCI_vital_insert_smoking
UNION
SELECT * FROM MRCI_vital_insert_TOBACCO
UNION
SELECT * FROM MRCI_vital_insert_TOBACCO_TYPE);
-----------------
/*Change variable type for vital data*/
CREATE OR REPLACE TABLE MCRI_MODIFIED_INSERT_IN_OBC_vital AS 
SELECT 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_VITAL_SINGS;
------
/*Change variable type for smoking data*/
CREATE OR REPLACE TABLE MCRI_MODIFIED_INSERT_IN_OBC_smoking AS 
SELECT 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_SMOKING_DATA;
------
/*Create table for linked vital_obsclin*/

Create or replace table mcri_linked_vital_obsclin as 
SELECT * FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_MODIFIED_INSERT_IN_OBC_SMOKING
UNION 
SELECT * FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.MCRI_MODIFIED_INSERT_IN_OBC_VITAL
UNION 
SELECT * FROM GROUSE_DB.PCORNET_CDM_MCRI.V_DEID_OBS_CLIN;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////MCW////////////////////////////////////////////////////////////

 /*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE MCW_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH  MCW_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE WT IS NOT NULL ),


MCW_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE HT IS NOT NULL),

MCW_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE original_bmi IS NOT NULL),

MCW_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE diastolic IS NOT NULL),

MCW_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE systolic IS NOT NULL )




SELECT * FROM MCW_vital_insert_WT
UNION
SELECT * FROM MCW_vital_insert_HT
UNION
SELECT * FROM MCW_vital_insert_BMI
UNION
SELECT * FROM MCW_vital_insert_DBP
UNION
SELECT * FROM MCW_vital_insert_SBP
);

------------------
/*change variable*/
create or replace table mcw_modefied_vital_obsclin as     
 SELECT 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT
    FROM MCW_INSERT_OBSCLIN_VITAL_SIGNS ;

/*Create table for smoking data*/
CREATE OR REPLACE TABLE MCW_SMOKING_DATA AS (
WITH MCW_vital_insert_smoking AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
smoking  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'smoking' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
smoking AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE smoking NOT IN ('NULL', 'OT','NI','','UN')

 ),

MCW_vital_insert_TOBACCO AS (SELECT 

NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE tobacco NOT IN ('NULL', 'OT','NI','','UN')
  ),

MCW_vital_insert_TOBACCO_TYPE AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco_type  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco_type' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco_type AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_VITAL
WHERE tobacco_type NOT IN ('NULL', 'OT','NI','','UN')


 )

SELECT * FROM MCW_VITAL_INSERT_SMOKING
UNION
SELECT * FROM MCW_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM MCW_VITAL_INSERT_TOBACCO_TYPE);

/*union both tables to create linke vital/obsclin table */
CREATE OR REPLACE TABLE MCW_linked_vital_obsclin AS
 
SELECT * FROM mcw_modefied_vital_obsclin
UNION 
SELECT * FROM MCW_SMOKING_DATA
UNION
SELECT * FROM GROUSE_DB.PCORNET_CDM_MCW.V_DEID_OBS_CLIN;



////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////UIOWA////////////////////////////////////////////////////////////////////


---All vital data are already exist in obclin table
 /*Records of ht not exsit in OBSCLIN table*/
---all records in vital are already exist in obsclin
--CREATE OR REPLACE TABLE KUMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where HT is not null
MINUS ( SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN  B 
where obsclin_code = '3137-7');



/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_wt AS 
 SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where WT is not null
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN   B 
WHERE obsclin_code = '3141-9';
 

//*BMI*/
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE Not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where original_bmi is not null
MINUS (SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN   B 
where obsclin_code = '39156-5');


//*DBP*/

/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL A 
where diastolic is not null
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN  B 
where obsclin_code = '8480-6'
 ;

//*SBP*/

/*create table for data in vital table not exists in obclin*/
---CREATE OR REPLACE TABLE Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date,a.measure_time, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_VITAL  A 
where systolic is not null
MINUS SELECT b.patid, b.obsclin_start_date,b.obsclin_start_time, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UIOWA.LDS_OBS_CLIN  B 
where obsclin_code = '8462-4';


/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////UNMC//////////////////////////////////////////////////////////////



 ---------------------------------
 /*Records of ht not exsit in OBSCLIN table*/
---all ht data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where HT is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where OBSCLIN_CODE  in ('8302-2','3137-7');


//*wt*/
 
/*create table for data in vital table not exists in obclin*/
---all wt data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where wt is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where obsclin_code in ('29463','3141-9') ;
 //


//*BMI*/
---all bmi data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where original_bmi is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where raw_obsclin_code = '39156-5';
//



//*DBP*/
/*check for different BMI names in obclin*/
---all dbp data  in vital are already exist in obsclin
---CREATE OR REPLACE TABLE UNMC_Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where diastolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where raw_obsclin_code = '8462-4';

//*SBP*/
/*create table for data in vital table not exists in obclin*/
---all sbp data  in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UNMC_Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_VITAL A 
where systolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UNMC.LDS_OBS_CLIN  B 
where raw_obsclin_code = '8480-6';



//////////////////////////////

/*Create table for smoking data*/
CREATE OR REPLACE TABLE UNMC_SMOKING_DATA AS (
WITH UNMC_vital_insert_smoking AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
smoking  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'smoking' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
smoking AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UNMC.V_DEID_VITAL
WHERE smoking NOT IN ('NULL', 'OT','NI','','UN')

 ),

UNMC_vital_insert_TOBACCO AS (SELECT 

NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UNMC.V_DEID_VITAL
WHERE tobacco NOT IN ('NULL', 'OT','NI','','UN')
  ),

UNMC_vital_insert_TOBACCO_TYPE AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco_type  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco_type' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco_type AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UNMC.V_DEID_VITAL
WHERE tobacco_type NOT IN ('NULL', 'OT','NI','','UN')

)

SELECT * FROM UNMC_VITAL_INSERT_SMOKING
UNION
SELECT * FROM UNMC_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM UNMC_VITAL_INSERT_TOBACCO_TYPE);

/*Modify colunm data type*/
create or replace table UNMC_Modified_INSERT_IN_OBC_SMOKING as

select 
 OBSCLIN_TYPE ,
 RAW_OBSCLIN_CODE ,
 OBSCLIN_START_TIME,
 RAW_OBSCLIN_NAME ,
 CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
 OBSCLIN_ABN_IND ,
 RAW_OBSCLIN_MODIFIER ,
 OBSCLIN_RESULT_UNIT ,
 OBSCLIN_PROVIDERID ,
 RAW_OBSCLIN_TYPE ,
 OBSCLIN_RESULT_SNOMED ,
 OBSCLIN_STOP_TIME ,
 OBSCLIN_CODE ,
 OBSCLINID ,
 OBSCLIN_RESULT_MODIFIER ,
 OBSCLIN_SOURCE ,
 RAW_OBSCLIN_UNIT ,
 CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
	ENCOUNTERID ,
 OBSCLIN_RESULT_QUAL ,
 OBSCLIN_START_DATE,
 OBSCLIN_RESULT_TEXT ,
 OBSCLIN_STOP_DATE ,
	PATID 

 

from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE. UNMC_SMOKING_DATA
;


/*The final linked table*/
create or replace table UNMC_linked_vital_obsclin_table as
SELECT * FROM UNMC_SMOKING_DATA
UNION
SELECT * FROM GROUSE_DB.PCORNET_CDM_UNMC.V_DEID_OBS_CLIN;
;


////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////UTHOUSTON/////////////////////////////////////////////////////////

 /*Records of ht not exsit in OBSCLIN table*/
CREATE OR REPLACE TABLE UNMC_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date, a.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A 
where HT is not null
MINUS SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%height%');

select * from GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN
limit 100;
 
 /*Create table for data exists in vital not obsclin*/
Create or replace table  UNMC_insert_obsc_ht as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UNMC_not_exsit_in_obslcin_ht b on b.patid = a.patid
 and b.encounterid = a.encounterid and b.MEASURE_DATE = a.measure_date ;

//*wt*/
 
/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_wt AS 
SELECT a.patid, a.measure_date, a.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A 
where wt is not null
MINUS SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%weight%');
 //



/*Create table for data exists in vital not obsclin*/
Create or replace table UTHOUSTON_insert_obsc_wt as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_wt b on b.patid = a.patid
  and a.encounterid = b.encounterid and b.MEASURE_DATE = a.measure_date ;



//*BMI*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_bmi AS 
SELECT a.patid, a.measure_date, a.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A 
where original_bmi is not null
MINUS SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%bmi%');
//

/*create table for data in vital table not exists in obclin*/

/*Create table for data exists in vital not obsclin*/
Create or replace table UTHOUSTON_insert_obsc_bmi as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_bmi b on b.patid = a.patid
  and   b.MEASURE_DATE = a.measure_date ;


//*DBP*/
/*check for different BMI names in obclin*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_dbp AS 
SELECT a.patid, a.measure_date, encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A 
where diastolic is not null
MINUS SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%diastolic%');



/*Create table for data exists in vital not obsclin*/

Create or replace table UTHOUSTON_insert_obsc_dbp as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_dbp b on b.patid = a.patid
  and   b.MEASURE_DATE = a.measure_date ;



//*SBP*/


/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE UTHOUSTON_not_exsit_in_obslcin_sbp AS 
SELECT a.patid, a.measure_date, encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A 
where systolic is not null
MINUS SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN  B 
where (lower (b.RAW_OBSCLIN_NAME) LIKE  '%systolic%');



/*Create table for data exists in vital not obsclin*/
Create or replace table UTHOUSTON_insert_obsc_sbp as
 select a.* from GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UTHOUSTON_not_exsit_in_obslcin_sbp b on b.patid = a.patid
  and   b.MEASURE_DATE = a.measure_date ;
//////////////////////////////
////////////////////////
/*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE UTHOUSTON_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH UTHOUSTON_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_insert_obsc_bmi
WHERE original_bmi IS NOT NULL),

UTHOUSTON_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_insert_obsc_dbp
WHERE diastolic IS NOT NULL),

UTHOUSTON_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_insert_obsc_Sbp
WHERE systolic IS NOT NULL )


SELECT * FROM UTHOUSTON_vital_insert_BMI
UNION
SELECT * FROM UTHOUSTON_vital_insert_DBP
UNION
SELECT * FROM UTHOUSTON_vital_insert_SBP
);
------
 

/*Modify colunm data type*/
create or replace table UTHOUSTON_Modified_INSERT_IN_OBC_ALL as

select 
 
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT


from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHOUSTON_INSERT_OBSCLIN_VITAL_SIGNS
;

select * from UTHOUSTON_Modified_INSERT_IN_OBC_ALL;

/*LINKE TO MAIN OBSCLIN TABLE */
CREATE OR REPLACE TABLE UTHOUSTON_LINKED_VITAL_OBSCLIN AS
SELECT * FROM UTHOUSTON_Modified_INSERT_IN_OBC_ALL
UNION
SELECT * FROM GROUSE_DB.PCORNET_CDM_UTHOUSTON.V_DEID_OBS_CLIN;
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////UTHSCSA///////////////////////////////////////////////////////////////////////
/*vital inserted to obsclin */
CREATE OR REPLACE TABLE UTHSCSA_INSERT_OBSCLIN_VITAL_SIGNS AS (

WITH  UTHSCSA_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE WT IS NOT NULL ),


UTHSCSA_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE HT IS NOT NULL),

UTHSCSA_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE original_bmi IS NOT NULL),

UTHSCSA_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE diastolic IS NOT NULL),

UTHSCSA_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE systolic IS NOT NULL )




SELECT * FROM UTHSCSA_vital_insert_ht
union
SELECT * FROM UTHSCSA_vital_insert_wt
union
SELECT * FROM UTHSCSA_vital_insert_BMI
UNION
SELECT * FROM UTHSCSA_vital_insert_DBP
UNION
SELECT * FROM UTHSCSA_vital_insert_SBP

);


/*Modify colunm data type*/
create or replace table UTHSCSA_Modified_INSERT_IN_OBC_ALL as

select 
 
 OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT


from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UTHSCSA_INSERT_OBSCLIN_VITAL_SIGNS
;

/*SMOKING DATA */
CREATE OR REPLACE TABLE UTHSCSA_SMOKING_DATA AS 

WITH UTHSCSA_vital_insert_smoking AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
smoking  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'smoking' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
smoking AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE smoking NOT IN ('NULL', 'OT','NI','','UN')

 ),

UTHSCSA_vital_insert_TOBACCO AS (SELECT 

NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE tobacco NOT IN ('NULL', 'OT','NI','','UN')
  ),

UTHSCSA_vital_insert_TOBACCO_TYPE AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco_type  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco_type' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco_type AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_VITAL
WHERE tobacco_type NOT IN ('NULL', 'OT','NI','','UN')

)




SELECT * FROM UTHSCSA_VITAL_INSERT_SMOKING
UNION
SELECT * FROM UTHSCSA_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM UTHSCSA_VITAL_INSERT_TOBACCO_TYPE;

/*LINKED VITALA AND OBSCLIN*/
create or replace table UTHSCSA_LINKED_VITAL_OBSCLIN as 
SELECT * FROM UTHSCSA_Modified_INSERT_IN_OBC_ALL
UNION
SELECT * FROM UTHSCSA_SMOKING_DATA
UNION
SELECT * FROM GROUSE_DB.PCORNET_CDM_UTHSCSA.V_DEID_OBS_CLIN;
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////UTSW////////////////////////////////////////////////////////////////////////////

 /*Records of ht not exsit in OBSCLIN table*/
---all records in vital are already exist in obsclin
--CREATE OR REPLACE TABLE UTSW_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where HT is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN  B 
where OBSCLIN_CODE = '8302-2';

//*wt*/
 
/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE UTSW_not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL  A 
where wt is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN   B 
where OBSCLIN_CODE in ('29463-7' ,'3141-9') ;
 

//*BMI*/
--CREATE OR REPLACE TABLE UTSW_not_exists_in_obsclin_bmi AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where original_bmi is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN  B 
where OBSCLIN_CODE = '39156-5';
//


//*DBP*/
/*check for different BMI names in obclin*/
--CREATE OR REPLACE TABLE UTSW_Not_exists_in_obsclin_dbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where diastolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN   B 
where obsclin_code = '8462-4';


//*SBP*/


/*create table for data in vital table not exists in obclin*/
--CREATE OR REPLACE TABLE UTSW_Not_exists_in_obsclin_sbp AS 
SELECT a.patid, a.measure_date, a.encounterid 
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_VITAL A 
where systolic is not null
MINUS  SELECT b.patid, b.obsclin_start_date, b.encounterid
FROM GROUSE_DB.PCORNET_CDM_UTSW.LDS_OBS_CLIN  B 
where obsclin_code = '8480-6';


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////UU//////////////////////////////////////////////////////////////////////

/*Records of ht not exsit in OBSCLIN table*/

CREATE OR REPLACE TABLE UU_not_exsit_in_obslcin_ht AS 
SELECT a.patid, a.measure_date 
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL  A 
where HT is not null
MINUS  SELECT b.patid, b.obsclin_start_date
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_OBS_CLIN  B 
where OBSCLIN_CODE in ('8302-2','3137-7') ;


/*Create table for data exists in vital not obsclin*/
Create or replace table  UU_insert_obsc_HT as
 select a.* from GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UU_not_exsit_in_obslcin_ht b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;
 

//*wt*/
 
/*create table for data in vital table not exists in obclin*/
CREATE OR REPLACE TABLE UU_not_exists_in_obsclin_wt AS 
SELECT a.patid, a.measure_date
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL  A 
where wt is not null
MINUS  SELECT b.patid, b.obsclin_start_date
FROM  GROUSE_DB.PCORNET_CDM_UU.V_DEID_OBS_CLIN  B 
where OBSCLIN_CODE in ('29463-7', '3141-9') ;


/*Create table for data exists in vital not obsclin*/
Create or replace table  UU_insert_obsc_wt as
 select a.* from GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL A
 join grouse_db_quail.dq_clean_table.UU_not_exists_in_obsclin_wt b on b.patid = a.patid
  and b.MEASURE_DATE = a.measure_date ;

/*Transform vital table to obclin*/
CREATE OR REPLACE TABLE UU_INSERT_OBSCLIN_VITAL_SIGNS AS (
WITH  UU_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM grouse_db_quail.dq_clean_table.UU_insert_obsc_wt
WHERE WT IS NOT NULL ),


UU_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM grouse_db_quail.dq_clean_table.UU_insert_obsc_HT
WHERE HT IS NOT NULL),

UU_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL
WHERE original_bmi IS NOT NULL),

UU_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL
WHERE diastolic IS NOT NULL),

UU_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL
WHERE systolic IS NOT NULL )


SELECT * FROM UU_vital_insert_ht
union
SELECT * FROM UU_vital_insert_wt
union
SELECT * FROM UU_vital_insert_BMI
UNION
SELECT * FROM UU_vital_insert_DBP
UNION
SELECT * FROM UU_vital_insert_SBP

);



/*Modify colunm data type*/
create or replace table UU_Modified_INSERT_IN_OBC_ALL as

select 
 OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT

from GROUSE_DB_QUAIL.DQ_CLEAN_TABLE.UU_INSERT_OBSCLIN_VITAL_SIGNS
;

/*SMOKING DATA */
CREATE OR REPLACE TABLE UU_SMOKING_DATA AS 
WITH UU_vital_insert_smoking AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
smoking  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'smoking' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
smoking AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL
WHERE smoking NOT IN ('NULL', 'OT','NI','','UN')

 ),

UU_vital_insert_TOBACCO AS (SELECT 

NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL
WHERE tobacco NOT IN ('NULL', 'OT','NI','','UN')
  ),

UU_vital_insert_TOBACCO_TYPE AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
NULL AS OBSCLIN_TYPE,
NULL  AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
tobacco_type  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
NULL  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'tobacco_type' AS RAW_OBSCLIN_NAME,
NULL AS RAW_OBSCLIN_CODE,
NULL AS RAW_OBSCLIN_TYPE,
tobacco_type AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
NULL RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_VITAL
WHERE tobacco_type NOT IN ('NULL', 'OT','NI','','UN')

)



SELECT * FROM UU_VITAL_INSERT_SMOKING
UNION
SELECT * FROM UU_VITAL_INSERT_TOBACCO
UNION
SELECT * FROM UU_VITAL_INSERT_TOBACCO_TYPE;


/*LINKED VITALA AND OBSCLIN*/
create or replace table UU_LINKED_VITAL_OBSCLIN as 
SELECT * FROM UU_Modified_INSERT_IN_OBC_ALL
UNION
SELECT * FROM UU_SMOKING_DATA
UNION 
SELECT* FROM GROUSE_DB.PCORNET_CDM_UU.V_DEID_OBS_CLIN
;

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////WAHSU/////////////////////////////////////////////////////////////////////////

-----
/*vital Wt inserted to obsclin */
CREATE OR REPLACE TABLE WHASHU_OBSCLIN_VITAL AS (
WITH  WHASHU_vital_insert_wt AS (SELECT 
	NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'29463-7' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
WT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg' OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body weight' AS RAW_OBSCLIN_NAME,
'29463-7' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
WT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg' RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_WASHU.V_DEID_VITAL
WHERE WT IS NOT NULL ),


WHASHU_vital_insert_HT AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8302-2' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
HT  AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'cm' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body height'  AS RAW_OBSCLIN_NAME,
'8302-2' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
HT AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'cm' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_WASHU.V_DEID_VITAL
WHERE HT IS NOT NULL),

WHASHU_vital_insert_BMI AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'39156-5' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
original_bmi AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'kg/m2' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Body mass index (BMI) [Ratio]'  AS RAW_OBSCLIN_NAME,
'39156-5' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
original_bmi AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'kg/m2' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_WASHU.V_DEID_VITAL
WHERE original_bmi IS NOT NULL),

WHASHU_vital_insert_DBP AS (SELECT 
	
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8462-4' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
diastolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Diastolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8462-4' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
diastolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_WASHU.V_DEID_VITAL
WHERE diastolic IS NOT NULL),

WHASHU_vital_insert_SBP AS (SELECT 
NULL AS OBSCLINID,
PATID,
ENCOUNTERID,
NULL AS OBSCLIN_PROVIDERID,
MEASURE_DATE AS OBSCLIN_START_DATE,
MEASURE_TIME AS OBSCLIN_START_TIME,
MEASURE_DATE AS OBSCLIN_STOP_DATE,
MEASURE_TIME AS OBSCLIN_STOP_TIME,
'LC' AS OBSCLIN_TYPE,
'8480-6' AS OBSCLIN_CODE,
NULL AS  OBSCLIN_RESULT_QUAL,
NULL AS OBSCLIN_RESULT_TEXT,
NULL AS OBSCLIN_RESULT_SNOMED,
systolic AS OBSCLIN_RESULT_NUM,
NULL AS OBSCLIN_RESULT_MODIFIER,
'mm[Hg]' AS  OBSCLIN_RESULT_UNIT,
NULL AS OBSCLIN_SOURCE,
NULL AS OBSCLIN_ABN_IND,
'Systolic blood pressure'  AS RAW_OBSCLIN_NAME,
'8480-6' AS RAW_OBSCLIN_CODE,
'LC' AS RAW_OBSCLIN_TYPE,
systolic AS RAW_OBSCLIN_RESULT,
NULL AS RAW_OBSCLIN_MODIFIER,
'mm[Hg]' AS RAW_OBSCLIN_UNIT
FROM GROUSE_DB.PCORNET_CDM_WASHU.V_DEID_VITAL
WHERE systolic IS NOT NULL )



SELECT * FROM WHASHU_vital_insert_ht
union
SELECT * FROM WHASHU_vital_insert_wt
union
SELECT * FROM WHASHU_vital_insert_BMI
UNION
SELECT * FROM WHASHU_vital_insert_DBP
UNION
SELECT * FROM WHASHU_vital_insert_SBP

);
/*change variable*/
create or replace table modefied_vital_obsclin as 
select     
OBSCLINID,
PATID,
ENCOUNTERID,
OBSCLIN_PROVIDERID,
OBSCLIN_START_DATE,
OBSCLIN_START_TIME,
OBSCLIN_STOP_DATE,
OBSCLIN_STOP_TIME,
OBSCLIN_TYPE,
OBSCLIN_CODE,
OBSCLIN_RESULT_QUAL,
OBSCLIN_RESULT_TEXT,
OBSCLIN_RESULT_SNOMED,
CAST( OBSCLIN_RESULT_NUM AS VARCHAR(200))AS OBSCLIN_RESULT_NUM,
OBSCLIN_RESULT_MODIFIER,
OBSCLIN_RESULT_UNIT,
OBSCLIN_SOURCE,
OBSCLIN_ABN_IND,
RAW_OBSCLIN_NAME,
RAW_OBSCLIN_CODE,
RAW_OBSCLIN_TYPE,
CAST( RAW_OBSCLIN_RESULT AS VARCHAR(200)) AS RAW_OBSCLIN_RESULT,
RAW_OBSCLIN_MODIFIER,
RAW_OBSCLIN_UNIT

FROM WHASHU_OBSCLIN_VITAL;
